### ISSUE TITLE
Error creating diagram: Unexpected editor: null

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2-core#1]
## Summary
I went to the Outline view, right-clicked on a system implementation, and selected Create diagram...

I got a pop-up with the name and Structure Diagram selected.  I pressed OK.

After a few seconds delay, I got an error pop-up from org.osate.ge that gave me the title of this issue.  Here is a cut-and-paste of a few lines from the log:

!ENTRY org.osate.ge 0 0 2018-05-16 08:13:01.827
!MESSAGE org.osate.ge.internal.ui.handlers.CreateDiagramHandler.execute(): CreateDiagramHandler Started

!ENTRY org.eclipse.e4.ui.workbench.swt 4 2 2018-05-16 08:13:55.005
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.e4.ui.workbench.swt".
!STACK 0
java.lang.NoSuchFieldError: ASYMMETRICAL
	at org.osate.ge.internal.diagram.runtime.layout.ElkGraphBuilder.createElkGraphElementForNonLabelAndUndockedShape(ElkGraphBuilder.java:459)
	at org.osate.ge.internal.diagram.runtime.layout.ElkGraphBuilder.lambda$2(ElkGraphBuilder.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
        ......

## Expected and Current Behavior
Expected a diagram to appear rather than a fatal error pop-up.

## Steps to Reproduce
The model is too large to cut-and-paste here, but I can SAFE it if desired.  I was able to reproduce this.

## Environment

* **OSATE Version**: Nightly test as of the date of this issue
* **Operating System**: Windows 10

**Comment by stevevestal** [comment]
How is the ELK dependency being handled now?  Is the exact version needed bundled with OSATE nightly?  Or when I install OSATE nightly into an existing eclipse, do I still need to be explicit about the ELK dependency?  What is the exact ELK URL to use?

**Comment by lwrage** [comment]
Wrong issue tracker. I've re-filed this as https://github.com/osate/osate2/issues/1245
