### ISSUE TITLE
Can't setup OSATE dev environment due to inaccessible xsemantics update site

### ISSUE THREAD

**Issue by jasonbelt** [osate/osate2-core#1000]
[osate2.setup](https://github.com/osate/osate2-core/blob/27a5dcc57b8540ef0dcd0e3807bad7e0b3b63587/osate.releng/osate2.setup#L827) refers to the update site for [xsemantics](https://dl.bintray.com/lorenzobettini/xsemantics/updates/1.12/), but it has been returning 403 responses since at least Jan 4.  The developer addresses the issue via this [GitHub issue](https://github.com/eclipse/xsemantics/issues/101) but doesn’t appear to know if the issue with bintray is temporary.

**Comment by lwrage** [comment]
Supposedly it's back. Please try again.
