### ISSUE TITLE
Update OSATE user guide

### ISSUE THREAD

**Issue by lwrage** [osate/osate2-core#1012]
Need basic intro, suitable for new users, to workspace, projects (and dependencies), predeclared property sets, text editor, menus, instantiation, how to run analyses.
Need tutorial with a simple example model, run through the mechanics of one analysis (latency?) without detailed explanation of the analysis itself.

**Comment by lwrage** [comment]
Should be written in markdown.

**Comment by lwrage** [comment]
Should also run through cloning the examples github repo and importing a project from the clone.

**Comment by AaronGreenhouse** [comment]
markdown tools:
- Visual editor: Haroopad <http://pad.haroopress.com/>
- Document translator: pandoc <https://pandoc.org/>

**Comment by AaronGreenhouse** [comment]
Original markdown spec & tutorial: https://daringfireball.net/projects/markdown/

**Comment by AaronGreenhouse** [comment]
Take some info from here: http://osate.org/setup-development.html

**Comment by AaronGreenhouse** [comment]
From Lutz:

> The core documentation is mostly outdated, so everything needs to be rewritten or deleted. This task is about basic getting started documentation. It doesn't have to be exhaustive, it's also not about any of the analyses.
> 
> It should replace the content of org.osate.help/html/start.
> 
> Please put all images in a subdirectory named images.
> 
> The content of the propview directory is new and should remain. Maybe read throug it and see if everything is correct.
> 
> For images, please use png (with file extension png, not PNG). IIRC, Windows likes the upper case version.

**Comment by AaronGreenhouse** [comment]
Done with the content. 

Not sure exactly how we want to integrate this.

For now I have done the following:
- The "source" is in the `org.osate.help/markdown` directory.
- I made one big `OSATEUserGuide.md` file.  For now there are some separate smaller files still in the directory, but they have all been incorporated into this one.
- I have `examples/` and `images/` subdirectories
- I used Haroopad to export an html file: `OSATEUserGuide.html`.  This is also in the markdown directory.
- But the files that are actually used by the help system I have put in `html/start2`
  - I copied `OSATEUserGuide.html` here
  - I copied `examples/` here
  - I copied `images/` here
- I hand edited `aadlhelp.html` to point to `html/start2/OSATEUserGuide.html`

**Comment by AaronGreenhouse** [comment]
Added PropertyViewExamples to the examples git repository.

**Comment by AaronGreenhouse** [comment]
Added section on imported from git.  Changed so that the examples come from the examples/ git repository.

**Comment by AaronGreenhouse** [comment]
Per Lutz's request I removed the syntax and style guides.  I have copied that material into `markdown/archived/`
