### ISSUE TITLE
Intermittent hang when instantiating models

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2-core#1024]
Every once in awhile, when I instantiate a model with the nightly test build, it hangs and I have to abort Eclipse.  The message at the bottom of the Progress Information popup is "Caching property associations in module."

**Comment by lwrage** [comment]
I haven't been able to reproduce the issue. Is this with a specific model, or does it occur across a variety of models. If it's with a specific model, can you share it?

**Comment by lwrage** [comment]
Also, is this when the declarative model contains errors, or does it also happen for decarative models without errors?

**Comment by stevevestal** [comment]
It's intermittent.  I cannot reliably reproduce it.  It happens maybe every couple of dozen instantiations.  It happens with different models.  The models do not contain syntax or legality errors.  I am running plugins from within a plugin development environment (Run as Eclipse Application); It's possible that might make a difference.  I have also seen the slightly different message, "Caching property associations in app."

**Comment by lwrage** [comment]
If this happens again, please create a thread dump and attach it to this issue. Without that it's impossible to know what's going on.

**Comment by stevevestal** [comment]
[jstackdump.txt](https://github.com/osate/osate2-core/files/1680048/jstackdump.txt)
Got one.  I was running this from an RCP development environment, "Run as Eclipse application."  Task Manager only listed a single eclipse.exe, though.  That's the process this thread dump came from.

**Comment by lwrage** [comment]
Unfortunately, that stack trace doesn't come from OSATE but from the development eclipse. 
In the task manager OSATE be listed as an application whose name should include "OSATE2", from there you can go to the process via the context menu. I see the process as "javaw.exe."

**Comment by stevevestal** [comment]
Try this one.
[jstackdump.txt](https://github.com/osate/osate2-core/files/1683030/jstackdump.txt)

**Comment by lwrage** [comment]
That thread dump was helpful. I could reproduce the deadlock when instantiating a component implementation from an AADL file that has errors. In my case the AADL file has property associations for MILS and FASTAR properties, but I don't have these property sets. I have no idea how this can possibly happen with a model that doesn't have errors, though.
