### ISSUE TITLE
AADL Package Wizard Allows Creating Package with Conflicting Names

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2-core#1044]
The AADL package wizard does not check if there is a package with the same name referencable by the project. If there is a conflicting package in a separate folder, the wizard will complete, but the new package will have an error.

**Comment by lwrage** [comment]
Is there code that checks for duplicates in the old "AADL Package (graphical)" wizard?

**Comment by philip-alldredge** [comment]
I don't believe so. It was originally forked from an old version of OSATE's wizard. It only checked for duplicate file names. Since it didn't allow the user to choose a folder, it was a little less likely for this situation to occur but it was still possible.

**Comment by lwrage** [comment]
Need to check if the new package name is already used in the global scope of the current project.

**Comment by AaronGreenhouse** [comment]
Regarding looking names, Joe says:

> The way to do this is to use `IGlobalScopeProvider`. This is used for looking up objects in different files in a way that respects project references. The global scope is a part of the larger subject of scoping in Xtext. Chapter 10 of the Xtext book deals with scopes.`IGlobalScopeProvider` needs to be injected. If you are not in a class that itself was created using injection, then you will have to manually call the injector before using the scope provider. An example of this can be found in the workflow class `AbstractPropertyDialog`. In that case, the constructor calls `injectMembers(this)` which will supply an object for the `globalScopeProvider` field.The method `getScope` will return an `IScope` which describes all of the objects visible from a particular `Resource` with a particular `EReference`. The reference is where things can get a little clunky. You can’t simply ask the global scope to give you all visible objects of a certain type. You have to instead have to ask for all visible objects that can fill a particular reference. So we simply have to pick a reference for which `AadlPackage` is a valid type. The reference `Aadl2Package.eINSTANCE.getPackageRename_RenamedPackage()` fits that requirement since the required type of that reference is `AadlPackage`.

> Internally, `AbstractGlobalScopeProvider` gets the required type of the reference, then searches for all objects of that type. It would be nice if we could simply pass an `EClass` instead of an `EReference`, but the method that takes an `EClass` isn’t public.

**Comment by AaronGreenhouse** [comment]
Updated `AbstractNewFileWizard` to have a `validateFileName()` method.  The default implementation is consistent with what `AbstractNewFileWizard` was already checking.

Updated `NewAadlPackageWizard` to override the method to check the package name using the name binder.   This was tricky.  I wanted to use the selected `IContainer` from the wizard to convert to a `Resource` for the name lookup.  But this doesn't work if the selected parent is the project.  So I create a `IFolder` reference to a fake folder (good thing that `IResource` references don't actually have to point to things that exist), and convert that to a `Resource` instead.

Next problem was that I have to convert the package name into a `QualifiedName` for lookup.  That's easy enough, use `String.split(..., "::")` to get the name segments and create a new qualifed name from them.

Then I just have to check if that package name is already in scope.  If it is, put up an error message

**Comment by lwrage** [comment]
There's a QualifiedNameConverter.

**Comment by AaronGreenhouse** [comment]
The catch here is that if you have a project `b` that depends on `a`, and 
- `a` has package `p1`
- `b` has package `p2`
then 
- trying to create a `p1` in `b` will yield an error, **but**
- trying to create a `p2` in `a` will not yield an error (in the wizard)

**Comment by AaronGreenhouse** [comment]
I Found QualifiedNameValueConverter, but I don't see how that helps.

**Comment by AaronGreenhouse** [comment]
Unit testing for this should also include testing package names that are keywords, e.g., `mode`, `flow`, `package`, etc.
