### ISSUE TITLE
Review and revise preference settings

### ISSUE THREAD

**Issue by lwrage** [osate/osate2-core#1061]
- [x] Check labels and organization in tree
- [x] Are there old unused preferences? (e.g., "default values in XML")
- [x] Do all Xtext generated preferences make sense?
- [ ] Merge annex preferences with core prefs
- [x] Add workspace pref for SOM limit
- [x] Link to SOM workspace pref from project pref
- [ ] Make sure preference settings are documented

**Comment by AaronGreenhouse** [comment]
The "Store default attribute values in XML file" preference is never used.  Preference ID is `WorkspacePlugin.EXPAND_DEFAULT_FLAG`.

**Comment by AaronGreenhouse** [comment]
Are we just concerned with the preferences that are under "OSATE Preferences" ?  Some of the plugins have preference pages elsewhere.  Is the idea to organize all of them?

**Comment by AaronGreenhouse** [comment]
"Flow Analysis" preferences should be under a general "Analysis" sub-heading.

**Comment by AaronGreenhouse** [comment]
What is Ocarina?

**Comment by AaronGreenhouse** [comment]
"Aadl2 Text Editor" an "ErrorModel Textual Editor" I assume are generated by the Xtext.  The naming should be made consistent: probably both should be **Text Editor**.  That is the common usage, although it would be more correct and consistent with the next point if we used **Textual**.  Thoughts?

"Diagrams" should be **Aadl Graphical Editor**.

We would have to also go through OSATE in general and make sure we use "Textual Editor" and "Graphical Editor" consistently.

**Comment by AaronGreenhouse** [comment]
How would a workspace preference for SOM limit interact with the project limit?  I assume we would defer to the workspace limit if the a project doesn't have a specific preference set.  When a project edits the limit for the first time, the project limit would be initialized to the workspace limit.

**Comment by AaronGreenhouse** [comment]
Is the error model editor a separate thing, or is it really a sub-parser that operates inside the regular AADL editor?  If that is the case, why does it have separate syntax-coloring preferences?

**Comment by AaronGreenhouse** [comment]
Renamed "OSATE Preferences" -> "OSATE"
Renamed "Aadl2 Text Editor" -> "AADL Text Editor"

**Comment by AaronGreenhouse** [comment]
Created branch `1061_update_preferences` on project repository `ErrorModelV2`

**Comment by AaronGreenhouse** [comment]
Commented out the installation of the "error model textual editor" preferences in the plugin.xml file.

**Comment by AaronGreenhouse** [comment]
Changed the "AADL Text Editor" preferences to not have the "remember prompts" button.

**Comment by AaronGreenhouse** [comment]
Removed the "Properties" preferences from the plugin.xml file.

**Comment by AaronGreenhouse** [comment]
Fixed the preference pane to be called "Flow Latency Analysis".  
- Updated the labels in the preferences to be consistently named and not use fun capitalization.

**Comment by AaronGreenhouse** [comment]
Removed "Instance" pane from the project project properties

**Comment by AaronGreenhouse** [comment]
Removed "Task Tags" project properties pane from the aadl2 text editor plug-in

**Comment by AaronGreenhouse** [comment]
Updated the "Instance" preference pane:
- Renamed to "Instance Model Text Editor"
- Moved to be under "OSATE"
- Removed "Templates"
- Removed "Refactoring"

**Comment by AaronGreenhouse** [comment]
Created `org.osate.ui.preferences.BlankPreferencePage` in `org.osate.ui`.  Made it publicly accessible.  

Added new, blank, preference page "Analysis" under "OSATE"

**Comment by AaronGreenhouse** [comment]
Update flow latency preference pane again:
- Moved to be under `OSATE > Analysis`
- Changed name to `Flow Latency` from `Flow Latency Analysis` because the analysis is now in the preference tree.
- Added `setDescription` call back to the preference page implementation.

**Comment by AaronGreenhouse** [comment]
Replaced `OsatePreferencePage` with `BlankPreferencePage` in `org.osate.ui`.  Didn't change or remove `OsatePreferencePage` in case we need it again.

**Comment by AaronGreenhouse** [comment]
Created branch `1061_update_preferences` on project repository `osate-ge`

**Comment by AaronGreenhouse** [comment]
In `osate-ge`, changed the name of the preference pane to "AADL Diagram Editor" to be consistent with "AADL Text Editor"

**Comment by AaronGreenhouse** [comment]
in `osate2-core`, package `org.osate.ui`:
- Renamed `ProjectPropertiesPage` to `IntantiationPropertyPage`
- Added `BlankPropertyPage`
- Added (blank) "OSATE" property page as parent for "Instantiation" in `plugin.xml`

**Comment by AaronGreenhouse** [comment]
Added an "Instantiation" workspace preference under "OSATE".
- Created workspace preferences for the maximum number of system operation modes to generate.
- Updated the project property pane to have control over whether to use the project or workspace settings.
- Can open the workspace settings from the property dialog.

Work is loosely inspired by the example in <http://www.eclipse.org/articles/Article-Mutatis-mutandis/overlay-pages.html>

Need to see how to open the property dialog from the workspace preferences.

**Comment by AaronGreenhouse** [comment]
Updated `InstantiationPreferencePage` to link the property page in the style of the Java preferences.  Inspired by the functionality of `PropertyAndPreferencePage` which is private to the JDT and also has a version in Xtext.  It's a shame there is no public standardized version of this.  Also made use of `org.osate.ui.dialogs.ProjectSelectionDialog` which wasn't being used by anything (but must have had a use at some point).  Again, there should be an Eclipse standard version of this, but there isn't and there are copies of it all over the libraries.

**Comment by AaronGreenhouse** [comment]
Updated <https://wiki-int.sei.cmu.edu/confluence/display/AADL/OSATE+Preference+Settings>
