### ISSUE TITLE
Aadl2SemanticSequencer Should Use Editing Domain of Resource Set

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2-core#1063]
An issue with how the Aadl2SemanticSequencer handles annexes in related to the graphical editor has been found. The issue is that the graphical editor uses its own resource set and editing domain when performing changes. The reason for this is that it uses live resources and often manipulates the contents of the resource set and it is intended to avoid conflicts with other users of the resource set. When an xtext document is open, an editing domain should not be used because then xtext doesn't use editing domains.

However, the Aadl2SemanticSequencer uses the registered OSATE editing domain in all cases. If editing an xtext document then this doesn't cause an exception because a transaction is not required. However, if the document is not opened then not using the graphical editor's editing domain results in an exception due to a transaction not being active. 

The recommended solution is to use the editing domain associated with the semantic object. If an editing domain does not exist, then one should not be used.

**Comment by lwrage** [comment]
What do I need to do to reproduce the exception?

**Comment by philip-alldredge** [comment]
- In the graphical editor:
	- Attempt to create an EMV2 Error Type Library while the AADL source is not open. 	
	- Regarding to the issue discussed in my comment in the pull request https://github.com/osate/osate2-core/pull/1064#issuecomment-367127774... It isn't reproducable with the EMF GE support because it doesn't currently allow modifying of EMV annex subclause. However, I can trigger the issue with an unreleased plugin for a similarly implemented annex.
- Outside of graphical editor:
	- This would presumably occur if an AADL resource was manually opened in a resource set with a transactional editing domain and then an annex was modified using model objects.

**Comment by philip-alldredge** [comment]
To clarify, although the issue mainly affects the experimental GE plugins, it also is critical to an unreleased plugin which is under active development.

**Comment by lwrage** [comment]
I am a bit reluctant to merge the fix before the 2.3.2 release next week
because I don't know if it could have side effects elsewhere. It looks OK
to me, but that doesn't guarantee anything. Is it a OK for you if it's not
in 2.3.2?

On Thu, Feb 22, 2018 at 10:33 AM, philip-alldredge <notifications@github.com

**Comment by philip-alldredge** [comment]
I think that will be fine. The sequencer doesn't seem to run unless the annex object is modified. I'd prefer to get it in shortly after the release though.

**Comment by lwrage** [comment]
Yes, it would go in right after the release.
