### ISSUE TITLE
Looking for example for using AADL parsing in batch/standalone environment

### ISSUE THREAD

**Issue by virtuald** [osate/osate2-core#1098]
I would like to do processing on AADL files without needing to be in an eclipse UI environment. Here's where I'm at now:

* Ran `mvn install` on `osate2-core.releng/modules/pom.xml` to build the pieces I need locally (basically, `org.osate.aadl2.instance.textual` and dependencies)
* Created a simple program that executes `Aadl2StandaloneSetup.doSetup()`
* Retrieve an AADL resource from a resourceSet

The `doSetup()` fails because of missing eclipse related dependencies (org.eclipse.emf.transaction in particular) that don't seem to be published to maven central, but are only available via the eclipse p2 repositories.

Has anyone else tried to do this before? Perhaps a sample pom.xml that I could look at and figure out what I'm doing incorrectly? Or documentation? It would be great if there were a project somewhere that showed how one might go about doing this.

**Comment by lwrage** [comment]
The OSATE google group is a better place to ask questions like this.

**Comment by virtuald** [comment]
Fair enough.
