### ISSUE TITLE
Update documentation for the new AADL package wizard

### ISSUE THREAD

**Issue by lwrage** [osate/osate2-core#1109]
There is a screen shot of the old wizard in the graphical editor documentation (User Guide -> Getting Started -> Crerating a new AADL Package). Need to update and make sure that the text matches the new workflow to create a package with the diagram editor. 
Also, the wizard should say "Diagram editor" instead of "Graphical editor." Then the screen shot in OSATE Core Documentation -> Getting started -> Creating an AADL Model needs to be updated, too.

**Comment by AaronGreenhouse** [comment]
Changed the label in the wizard.

Updated the screen shot in the document.
