### ISSUE TITLE
Hung when rebuilding workspace after a git pull

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2-core#1112]
The workspace only had AADL models.  I did a pull from a git repository, and then Eclipse hung shortly after the notice a workspace build was occurring appeared.  I'm attaching the stack dump.   This seems to leave the workspace corrupted.  When I restart Eclipse, it immediately hangs doing an initial build.

[jstackdump.txt](https://github.com/osate/osate2-core/files/1865467/jstackdump.txt)

**Comment by stevevestal** [comment]
This may be a version issue.  I was able to load the model (the one I did a git pull on) using OSATE stable 2.3.2, the version it was developed with.  I was loading it using an OSATE nightly test from a few days ago.  With a fresh workspace, I got an error at launch about sirius being out-of-date (it wasn't installed).  I tried installing the latest stable and the nightly for that, but without success.  Does that need to be manually installed in addition to OSATE nightly?  If so, which download URL (which exact version) of sirius is used with the nightly?

**Comment by lwrage** [comment]
Sirius is part of the nightly build. Both osate 2.3.2 and the nightly come with sirius 5.1.0.

**Comment by stevevestal** [comment]
We removed that from the repository to avoid the hang.  Now when we import from the repository, we get messages like the following.  The nightly build doesn't seem backwards-compatible with projects created using 2.3.2.

Zero representations file found in "AirVehicle". A modeling project must contain one.

**Comment by stevevestal** [comment]
By "removed that," I meant the resources.aird (or whatever) file that appeared in some but not all.

**Comment by lwrage** [comment]
There seem to be multiple intermixed issues here:
1. The hang during the initial build. The stack trace looks similar to #1111, so maybe it's the same issue. However, I am not able to reproduce that. Can you reproduce it? If yes, can you share the workspace where the issue occurs?
2. The sirius version issue: I'll refer this to @reteprelief . Maybe he has made a breaking change to the fault tree diagrams.
3. You've removed the `resources.aird`, which causes issues with the modeling project nature. You can fix that by removing this nature from the project. Right click on the project in the AADL navigator -> Configure -> Remove Modeling Project Nature. Related: #1101
