### ISSUE TITLE
Graphical editor documentation contains broken links

### ISSUE THREAD

**Issue by lwrage** [osate/osate2-core#1213]
## Summary

The graphical editor user guide contains references to images using capitalization that does not exactly match the file names. This does not work on Linux because the file system is case sensitive it also wouldn't work if we had a Web version of the documentation.

## Environment

* **OSATE Version**: nightly
* **Operating System**: Linux

**Comment by philip-alldredge** [comment]
Fixed merged in osate/osate-ge@6f81e653ce6795fca07dd198696ba3a11cf90032
