### ISSUE TITLE
Broken references in GE developer guide

### ISSUE THREAD

**Issue by lwrage** [osate/osate2-core#1215]
## Summary

The graphical editor developer guide references various non-existing html files:
- api/org/osate/ge/di/BuildReference.html
- api/org/osate/ge/di/ResolveReference.html
- api/org/osate/ge/GetGraphicalConfiguration.html
- api/org/osate/ge/di/GetChildren.html
- api/org/osate/ge/di/SetName.html

## Environment

* **OSATE Version**: nightly
* **Operating System**: Linux

**Comment by philip-alldredge** [comment]
Fixed in osate/osate-ge@a79cc1c4b7d340652088cecf55e49580418d002b
