### ISSUE TITLE
getClassifier method on Feature does not return FeatureGroupType for FeatureGroup

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2-core#154]
getClassifier is a method (I think defined in the Meta model) to return the classifier.
By default it returns null. 
Each class that has a classifier should return the classifier.
In case of the feature group we have a method getFeatureGroupType, but not the generic getClasssifier that would do the same.

I had a place in validation where caseFeature was calling on getClasssifier.
At this time I addressed the issue by checking for the class and then calling getFeatureGroupType instead of getClassifier.

**Comment by lwrage** [comment]
Doesn't seem worth fixing.
