### ISSUE TITLE
ForAllElement.defaultTraversalAllDeclarativeModels() doesn't give Component types in Plugin_Resource

### ISSUE THREAD

**Issue by mnam** [osate/osate2-core#180]
Hi all,

Not sure if this was intended or its a bug.
The defaultTraversalAllDeclarativeModels does NOT go through any of 
component types in the Plugin_Resources. 
The standard of course doesn't have any Classifier types defined in the Plugin_Resources.
However, we can add plug-ins to extend it and as a use case, one would add
a library of components that a tool supports so that people could extend them.
To provide the list of these library components as well as any component type definition,
I would use defaultTraversalAllDeclarativeModels  but the types are not included.

On the other hand, using the EMFIndexRetrieval approach, I do get ALL type definitions.
Any way we could make the defaultTraversalAllDeclarativeModels work for content in the
Plugin_Resources or is there any settings I could do?

Thanks.
Min Young

**Comment by lwrage** [comment]
This is pretty old. Do we still need to fix it?

**Comment by mnam** [comment]
I must have done something about this.
Frankly, I don't remember since it has been so long.
Let's close this.

Thanks.
Min Young
