### ISSUE TITLE
problem updating from update site

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2-core#216]
If you install the product version of OSATE from the testing branch and then try to do an update from the update site, it will give an error message that it cannot do an install, but will attempt an update instead. However, the next button is not enabled.
If you then invoke About under Help and then installation details, you can select the OSATE2 installation and the update button at the bottom is enabled and the update install works.

Looks like a possible issue with Eclipse or some setting in our configuration.

**Comment by lwrage** [comment]
This works in the current testing version.
