### ISSUE TITLE
Connection references in instance model should identify connected features in feature groups

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2-core#246]
When the connection from a port becomes part of a feature group the ConnectionReference object representing a connection in the connection instance higher in the hierarchy points to the enclosing feature group instance and not the feature instance representing the port. When pointing to the port we can easily get the enclosing feature group (getOwner()), while doing it the other way is more work.

This gets to the question of what the ConnectionReferences are for and who uses them.
The graphical editor uses the information to find the port or enclosing feature group that the connection line should be attached to for connections up in the hierarchy. This can be done by starting with the port and going to the parent until it finds the adapter that holds the figure for the feature.

The error model propagator uses it to find the EMV2 subclauses. They would be attached to the port rather than the enclosing feature group in many cases.

**Comment by lwrage** [comment]
We should also store information if a bidirectional connection is used in src -> dst or dst -> src order.

**Comment by lwrage** [comment]
Delaying, requires more thought.

**Comment by lwrage** [comment]
Pointing to actual feature was implemented in fdadeaa5cceded1a17a4e1cd82c4a6ad48ea6473

**Comment by lwrage** [comment]
Added a flag that indicates if we go in reverse of declaration direction: 727e3a9d60ea1fed66fd623f2263cd18a894d26c
