### ISSUE TITLE
Mismatched requires/requires connection not detected

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2-core#313]
When connecting two subsystems with bus access, you should not be able to connect them if both are requires (or provides).
If the feature is a requires bus access OSATE detects the mismatch.
But if the bus access feature is embedded inside a feature group it is not detected.
Example: this system seemed to bypass the same check
```
system implementation s3.i
subcomponents
       s11: system s1;
       s22 : system s2;
connections
-- this appears to escape the checking 
       s12: feature group s11.i1 -> s22.i2;
end s3.i;
see declaration below
feature group c1
       features
              b1 : requires bus access mybus;
end c1;
feature group c2
       features
              b1 : requires bus access mybus;
             inverse of c1
end c2;
              ^-- should we enforce a check here
```

**Comment by klreamsei** [comment]
This was fixed by validating the access kind in the feature group that is an inverse.
1bd9f4f034121fd84b95bb6342270ac512597f3b
