### ISSUE TITLE
feature groups with name mapping creates problem in instanitation

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2-core#314]
Bren has an example of FCM/OASM connectivity. When it uses name mapping to achieve cross-over in connections, too many connection instances are generated. It seems to iterate over the list of features in both FGTs to generate the connections.

If we do not use this, but declare the feature group as inverse of the FGT and then do the cross over when connecting the position isolator, everything works.

**Comment by lwrage** [comment]
Please reopen if this is still relevant.
