### ISSUE TITLE
In Data Port to Requires Data Access Connection Allowed

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2-core#362]
Currently OSATE allows an input data port to be connected to a subprogram call's requires data access. I believe this is in violation of the following rule: 

"If the port connection declaration represents a connection between ports down the containment hierarchy, then the source and destination must both be incoming ports. If the source connection end is a data access feature, then it must be a requires access feature; if it is a destination connection end it must be a provides access feature"

That said, I would like to model a subprogram that is passed variables by read-only reference using the currently frozen value from the data port. A data subcomponent could be used but I believe that would imply that the thread makes an additional copy of the data rather than just using the value frozen at thread dispatch time.

Example:

``````
package cs_test
public
    thread test_thread
    features
        indp : in data port test_data;
    end test_thread;

    subprogram test_sp
    features
        rda : requires data access test_data;
    end test_sp;

    thread implementation test_thread.impl
    calls
        cs1: {
                a: subprogram test_sp;
            };
    connections
        c2: port indp -> a.rda; -- Should not be allowed according to the standard?
    end test_thread.impl;

    data test_data
    end test_data;
end cs_test;```

``````

**Comment by lwrage** [comment]
We need to add a validation for this rule.

**Comment by klreamsei** [comment]
The standard seems to be mistaken here. Lutz cited several inconsistencies that need resolved.
