### ISSUE TITLE
Cannot edit property association with property editor

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2-core#397]
I can add a property association to c component classifier with the PA+ button.
When I invoke it again and select the same property it will add a second property association of that name. This should not happen. Note that the AADL Property Value viewer only shows the first property association with a given name.
Instead it would be nice to have a way of editing the value of an existing property association - maybe by just double  clicking in the AADL Property Value view on the value.

**Comment by joeseibel** [comment]
David,

Lutz asked me to assign the remainder of this issue to you.  Please look at the previous comment and you will see a list of items with many of them crossed out.  The ones that are not crossed out are yet to be done.

**Comment by ArslanIbnDaud** [comment]
* Add a checkbutton that restricts properties to just the properties defined in the current package (eg analogous to a 'with' statement)

* 'collapse all' button looks & feels just like in Eclipse's Navigation View

* 'sort' is a checkbutton. When on, each level of the tree appears in alphabetical order. When off, each level of the tree appears in declaration order. (Right now the order is arbitrary, prob sorted on URIs)

**Comment by lwrage** [comment]
The description for the first item is not quite accurate. The checkbutton should restrict the properties to those that are defined in either a predefined property set or a property set whose name is listed in a `with` statement in the current package. (Predefined property sets are in org.osate.workspace/resources/properties)

There is a sort button in the outline view. We should reuse its icon.

**Comment by ArslanIbnDaud** [comment]
Lutz says, via email:

In Osate, create a new aadl file ps.aadl:

property set ps is
  prop: aadlinteger applies to (system);
end ps;

Create another file x.aadl:

package X
public
   
    with ps;

    system S
    end S;

end X;

Open x.aadl in the editor and click on the name S. Now the property view shows property sets, including ps. If you remove the 'with ps;' line from x.aadl, ps is still shown in the AADL property view. Whenever the new filter is enabled, ps should be shown if and only if the with clause is in the aadl source file.

With the filter turned on, and when the current aadl file contains no with clause at all, only predefined property sets should be shown in the property view.

**Comment by ArslanIbnDaud** [comment]
I should add that the 'imported properties / with statement' button is in fact very similar to the 'show undefined' button. The feature only becomes necessary when undefined properties are shown; it's prob useless when they are hidden.

**Comment by lwrage** [comment]
These are the remaining items
- [ ] filter view by property sets occurring in`with` statements
- [ ] sort alphabetically (property set names and property names)

**Comment by aaronvolkmann** [comment]
I spoke with lwrange and we agreed that  "sort alphabetically (property set names and property names)" was already implemented elsewhere.

**Comment by aaronvolkmann** [comment]
implemented "filter view by property sets occurring inwith statements"  we may want to customize the icon in the future.
