### ISSUE TITLE
keeping package name and file name synchronized

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2-core#398]
OSATE currently lets you use file names that are different from package names. 
When I do that I have a hard time finding packages.
It would be nice to have the names synchronized - either enforced or enabled by preference.
In that case when the package name is changed the file name should be changed and possibly vice versa. 
One issue is when the packages have multiple :: separated identifiers.
In OSATE1 we used to map :: into another symbol.
An alternative is to do what Java does: in the file system use nested folders, while in the navigator show the full packagename without showing the folders..

**Comment by lwrage** [comment]
Please reopen if you think we really need this.
