### ISSUE TITLE
GetProperties methods returning null

### ISSUE THREAD

**Issue by brlarson** [osate/osate2-core#404]
GetProperties.getDispatchProtocol((NamedElement)context) is returning null, when it used to return "Periodic"
also these are returning null consistently:
      blessAssertion = GetProperties.lookupPropertyDefinition(f,"BLESS","Assertion");
      blessTyped = GetProperties.lookupPropertyDefinition(f,"BLESS","Typed");

I'm using develop branch pulled within the last 24 hours

**Comment by lwrage** [comment]
@brlarson Do you still see this behavior in a recent build?
