### ISSUE TITLE
resolving references as property values when associated with connections

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2-core#465]
We can have properties directly associated with connections by declaring them inside {}
The reference points to a subcomponent within the component for which the connection is declared, but it now is unresolved. It used to work.
The problem is that when we changed the reference resolution we only looked at the subcomponent case. In that case we interpret the applies to and the reference the same way, i.e., we start with the classifier of the subcomponent.
That does not make sense for connections.
See example https://github.com/osate/examples/blob/master/core-examples/misc/latency.aadl
or fanout.aadl.
There are a number of other examples that broke because of that as well.

**Comment by lwrage** [comment]
Fixed a while ago
