### ISSUE TITLE
Validate missing modes in modal property values

### ISSUE THREAD

**Issue by joeseibel** [osate/osate2-core#489]
We need to validate consistency rule C1 in section 11.3 (Property Associations):
> If a property association has mode-specific values, i.e., values declared with the **in modes** statement, then the modal value assignment must include a value for each mode. If the modal value assignment includes a value without the **in modes** statement, this value becomes the default for all modes without an explicit mode-specific value.

The validator should produce an error missing local or inherited modes.

**Comment by klreamsei** [comment]
This validation was added previously. Gives a warning instead of error.
