### ISSUE TITLE
Formatting and indentation

### ISSUE THREAD

**Issue by juli1** [osate/osate2-core#504]
When writing a model, the indentation is not correct. When writing a component and pressing enter, it automatically insert a tab. This would be ok if the tab is removed when writing the "end componentname" but instead, it keeps adding tab so that the user has to remove the tab himself.

This is very inconvenient when writing several lines of AADL. Removing the automatic tab insertion would improve the user experience.

**Comment by lwrage** [comment]
Automatic unindent should work now in the core language. Not in annexes!
There are a couple of preferences that allow customization of the behavior.
