### ISSUE TITLE
Properties view does not get updated when selection chenages

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2-core#547]
The Eclipse Properties view only gets updated when I select a different file.
When I select an item within an AADL editor - or for that matter in any instance of an Xtext based editor such as the Alisa grammars, the Properties view does not update to show the attributes of the selected object.

This occurs with the current sources. It seems to have started a little bit ago as I tried it on a testing release that was maybe two weeks old.

**Comment by lwrage** [comment]
It seems that this does not work with Xtext editors in general. (https://blogs.itemis.de/leipzig/archives/668). As a workaround you can open an AADL file in the instance editor.
