### ISSUE TITLE
Duplicated Icons

### ISSUE THREAD

**Issue by joeseibel** [osate/osate2-core#548]
There are duplicated icons in org.osate.aadl2.edit/icons/obj16 and org.osate.xtext.aadl2.ui/icons.  The icons should only be in org.osate.aadl2.edit and org.osate.xtext.aadl2.ui should use the ones in org.osate.aadl2.edit.

**Comment by philip-alldredge** [comment]
The graphical editor was switch to use the new directory. However, somewhere in the process many of the icons were replaced with generic icons. I believe it was in the cbae871. As a result the icons used by the graphical editor are no longer correct in OSATE 2.1.0 .

I have attempted to make a list of the incorrect icons. Can you please revert the changes to the following icons:

AbstractType
AbstractImplementation
AbstractFeature
AccessConnection
FeatureConnection
PortConnection
SubprogramAccess
SubprogramCallSequence
SubprogramGroupAccess
SubprogramGroupType
SubprogramGroupImplementation
SubprogramGroupSubcomponent
