### ISSUE TITLE
View menu in tool bar is repeated multiple times when diagrams are created.

### ISSUE THREAD

**Issue by three-jeeps** [osate/osate2-core#556]
working with osate  build 2/25/2015, windoz, 32bit (running on my 64 bit machine, most current Java version.  Creating multiple diagrams results in multiple "View" on the tool bar. - see below
![osate - multiple view problem](https://cloud.githubusercontent.com/assets/7050971/6420299/eadee186-be92-11e4-8a0c-e8daee432f91.jpg)

Scenario that created the behavior:
I loaded the resolute example from the wiki and everything was OK with the tool bar.  I wanted to view each implementation in the example so I created a diagram.  With each diagram it created a View menu was added to the tool bar.  I think I created 6 or 7 diagrams, and that is how many View menus were on the toolbar, each time I created a diagram, another View appeared.  They did not go away when I closed the diagram.  I ‘cleaned’ the project and they did not go away.  I closed OSATE and restarted it……All the View menus were gone..  I am fairly certain that this is the desired behavior…..

John

**Comment by philip-alldredge** [comment]
I just pushed a fix to the develop branch of the graphical editor.

As a reminder, the graphical editor has it's own repository and issue tracker(osate-ge).

**Comment by philip-alldredge** [comment]
I think this issue should be closed. I don't have the ability to close issue for this project.

**Comment by lwrage** [comment]
Fixed by osate/osate-ge@9915e1f9d34a19a05cad5500efec4286478622b7
