### ISSUE TITLE
Properties are not instantiated for abstract components

### ISSUE THREAD

**Issue by juli1** [osate/osate2-core#558]
Looking at the following model, after instantiating the model, the properties are not found in the instance model.

package puc::test

public

abstract initialization
features
	init_done : out event port;
flows
	init_flow : flow source init_done;
properties
	Dispatch_Protocol => Sporadic;
	Compute_Execution_Time => 3 ms .. 10 ms;
	Latency => 12 ms .. 42 ms;
end initialization;

abstract setup
features
	setup_request : in event port;
	setup_done : out event port;
flows
	setup_flow : flow path setup_request -> setup_done;
properties
	Compute_Execution_Time => 3 ms .. 10 ms;
	Dispatch_Protocol => Sporadic;
end setup;

abstract homing
features
	homing_request : in event port;
	homing_done : out event port;
flows
	homing_flow : flow path homing_request -> homing_done;
properties
	Compute_Execution_Time => 3 ms .. 10 ms;
	Dispatch_Protocol => Sporadic;
end homing;

abstract testing_activity
features
	request : in event port;
	done : out event port;
flows
	testing_flow : flow path request -> done;
properties
	Compute_Execution_Time => 3 ms .. 10 ms;
	Dispatch_Protocol => Sporadic;
end testing_activity;

abstract testing
features
	testing_request : in event port;
	testing_done : out event port;
flows
	testing_flow_sm : flow path testing_request -> testing_done;
	testing_flow_os : flow path testing_request -> testing_done;
	testing_flow_lp : flow path testing_request -> testing_done;
properties
	Compute_Execution_Time => 3 ms .. 10 ms;
	Dispatch_Protocol => Sporadic;
end testing;

abstract implementation testing.i
subcomponents
	sm : abstract testing_activity;
	os : abstract testing_activity;
	lp : abstract testing_activity;
connections
	sm_request : port testing_request -> sm.request;
	sm_done : port sm.done -> testing_done;
	os_request : port testing_request -> os.request;
	os_done : port os.done -> testing_done;
	lp_request : port testing_request -> lp.request;
	lp_done : port lp.done -> testing_done;
flows
	testing_flow_sm : flow path testing_request -> 
	                            sm_request -> sm.testing_flow ->
	                            sm_done -> testing_done;
	testing_flow_os : flow path testing_request -> 
	                            os_request -> os.testing_flow ->
	                            os_done -> testing_done;
	testing_flow_lp : flow path testing_request -> 
	                            lp_request -> lp.testing_flow ->
	                            lp_done -> testing_done;
end testing.i;

abstract bec
features
	bec_request : in event port;
	bec_done : out event port;
flows
	bec_flow : flow path bec_request -> bec_done;
properties
	Compute_Execution_Time => 3 ms .. 10 ms;
	Dispatch_Protocol => Sporadic;
end bec;

abstract finished
features
	completed : in event port;
flows
	finished_flow : flow sink completed;
properties
	Compute_Execution_Time => 3 ms .. 10 ms;
	Dispatch_Protocol => Sporadic;
end finished; 

system integrated
end integrated;

system implementation integrated.i
subcomponents
	initialization 	: abstract initialization;
	setup 			: abstract setup;
	homing 			: abstract homing;
	testing 		: abstract testing.i;
	bec 			: abstract bec;
	finished 		: abstract finished;
connections
	c0 : port initialization.init_done -> setup.setup_request;
	c1 : port setup.setup_done -> homing.homing_request;
	c2 : port homing.homing_done -> testing.testing_request;
	c3 : port testing.testing_done -> bec.bec_request;
	c4 : port bec.bec_done -> finished.completed;
flows
	etef_sm : end to end flow initialization.init_flow -> c0 ->
	                        setup.setup_flow -> c1 ->
	                        homing.homing_flow -> c2 ->
	                        testing.testing_flow_sm -> c3 -> 
	                        bec.bec_flow -> c4 ->
	                        finished.finished_flow;
	etef_os : end to end flow initialization.init_flow -> c0 ->
	                        setup.setup_flow -> c1 ->
	                        homing.homing_flow -> c2 ->
	                        testing.testing_flow_os -> c3 ->
	                        bec.bec_flow -> c4 ->
	                        finished.finished_flow;
	etef_lp : end to end flow initialization.init_flow -> c0 -> 
	                        setup.setup_flow -> c1 ->
	                        homing.homing_flow -> c2 ->
	                        testing.testing_flow_lp -> c3 ->
	                        bec.bec_flow -> c4 ->
	                        finished.finished_flow;	                        
end integrated.i;

	
	
end puc::test;

**Comment by lwrage** [comment]
@juli1 It would save me some time if you could add which properties are missing or have the wrong value on which component instance.

**Comment by juli1** [comment]
Well, if you try the model, all of them are missing, there are no property on any abstract components.
