### ISSUE TITLE
Missing classifier for instantiated prototype feature

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2-core#561]
-- Minor issue.  See comment starting line 26.
package ProtoParamClass
public
	
	bus BusType
	end BusType;
	
	system CompPrototype
	prototypes
		busTypeParam: bus;
	features
		aBus: requires bus access busTypeParam;	
	end CompPrototype;
	
	system CompInstance extends CompPrototype (busTypeParam => bus BusType)	
	end CompInstance;
	
	system Sys					
	end Sys;
	
	system implementation Sys.Imp
	subcomponents
		comp: system CompInstance;
		mem: bus BusType;
	connections
		-- Why the warning that comp.aBus is missing
		-- a classifier?  Doesn't the parameter instantiation
		-- on line 15 declare that the classifier is BusType?
		-- Implementations can be specified for everything
		-- and the warning is still issued.
		mbn: bus access mem <-> comp.aBus;		
	end Sys.Imp;			
		
end ProtoParamClass;

**Comment by lwrage** [comment]
The validator currently doesn't evaluate prototype actuals.

**Comment by lwrage** [comment]
See #641
