### ISSUE TITLE
Instantion of feature group connection generates extraneous port connections

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2-core#563]
-- See comment starting line 27.
package FGConnectInstance
public
	
	data MsgType
	end MsgType;
		
	feature group FGType
	features
		inPort: in data port msgType;
		outPort: out data port msgType;
	end FGType;
	
	process Proc
	features
		fgPorts: feature group FGType;
	end Proc;
	
	process InverseProc
	features
		fgPorts: feature group inverse of FGType;
	end InverseProc;
	
	system Sys
	end Sys;
	
	-- Instantiation of the following system results in
	-- an instance file that contains four port-to-port
	-- connections rather than two.  It includes a
	-- backwards connection from the in port to the out
	-- port as well as the expected forward connection
	-- from out port to in port.
	system implementation Sys.Imp
	subcomponents
		proc: process Proc;
		iproc: process InverseProc;
	connections
		fgc: feature group proc.fgPorts <-> iproc.fgPorts;
	end Sys.Imp;
		
end FGConnectInstance;

**Comment by lwrage** [comment]
Already fixed in the testing version.
