### ISSUE TITLE
No validation that a RangeValue upper limit is equal or greater than the lower limit

### ISSUE THREAD

**Issue by klreamsei** [osate/osate2-core#566]
property set ps1 is
	range1 : range of aadlinteger applies to (all);
end ps1;

package rangevaltest
public
	with ps1;
	abstract ab1
		properties
			-- this should be an error
			ps1::range1 => 10 .. 1;
	end ab1;
end rangevaltest;

**Comment by lwrage** [comment]
Don't forget units in the comparison, e.g., p => 100ms .. 1s
