### ISSUE TITLE
Multiple flow instances for a single feature group flow, some incorrect

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2-core#567]
-- I would have expected a single flow object to appear
-- in the instance file for the single flow declaration below.  There are
-- four of them.  The first two appear to be incorrect, the last two appear
-- to be correct but duplicates of each other.

-- I used OSATE 2.0.9 02 March 2015.  The fix for issue #565 could well
-- affect these results, I didn't check this with the most recent test build.

package FeatureGroupFlow
public
	
	feature group NestedPorts
	features
		outMsg: out event data port;
		inMsg: in data port;
	end NestedPorts;

	system BlackBox
	features
		etherCable0: requires bus access;	
		ioports: feature group NestedPorts;
	flows
		outFlow: flow source ioports.outMsg;
		inFlow: flow sink ioports.inMsg;
	end BlackBox;
	
	process ioProc
	features	
		ioports: feature group inverse of NestedPorts;
	flows
		thruFlow: flow path ioports.outMsg -> ioports.inMsg;	
	end ioProc;
	
	process implementation ioProc.Imp
	subcomponents
		t1: thread ioThread.Imp 
			{Dispatch_Protocol => Periodic;
			Period => 10 ms;
			Deadline => 5 ms;
			Priority => 1; 
			Compute_Execution_Time => 3 ms .. 3 ms;};
	connections
		c: feature group ioports <-> t1.ioports;			
	flows
		-- An explicit thruFlow is needed with feature group connections
		thruFlow: flow path ioports.outMsg -> c -> t1.thruFlow -> c -> ioports.inMsg;
		--thruFlow: flow path ioports.outMsg -> c -> t1 -> c -> ioports.inMsg;		
	end ioProc.Imp;
	
	thread ioThread
	features	
		ioports: feature group inverse of NestedPorts;
		anon: out data port;	
	flows
		thruFlow: flow path ioports.outMsg -> ioports.inMsg;			
	end ioThread;
	
	thread implementation ioThread.Imp
	end ioThread.Imp;
	
	system SystemFG
	end SystemFG;
		
	system implementation SystemFG.Instantiate_Me
	subcomponents
		module: processor;
		network: system;
		proc: process ioProc.Imp;
		box: system BlackBox;	
	connections
		c_bb_proc: feature group box.ioports <-> proc.ioports;
	flows
		f_bb_proc_bb: end to end flow box.outFlow -> c_bb_proc -> proc.thruFlow -> c_bb_proc -> box.inFlow;	
	properties
		Actual_Processor_Binding => (reference (module)) applies to proc;
		
		Actual_Connection_Binding => (
			reference(network)								
		) applies to c_bb_proc;	
		
	end SystemFG.Instantiate_Me;
	
end FeatureGroupFlow;

**Comment by lwrage** [comment]
The fix for #565 improves the situation but the flow in this example is still not instantiated correctly.

**Comment by lwrage** [comment]
In the example, one of the created connections has its connection references in the wrong order. This happens when the feature group connection is expanded into individual connections.
