### ISSUE TITLE
Missing Priority_Range legality checks

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2-core#584]
-- Missing checks for standard legality rules?

-- Section 11.1.1 paragraph (l1) states: 
-- The value of the first numeric literal that appears in a range 
-- of a number_type must not be greater than the value of the
-- second numeric literal including the value’s units.

-- Appendix A, table entry for Priority_Range states:
-- The Priority_Range property specifies the range of thread
-- priority values that are acceptable to the processor.

-- Instantiating the system still does not produce error messages.

package RangeOrder
public
	
	process AProc
	end Aproc;
		
	process implementation Aproc.Imp
		subcomponents
			task: thread;
	end Aproc.Imp;
	
	system ASys
	end ASys;
		
	system implementation ASys.Imp
	subcomponents
		hostA: processor {Priority_Range => 32 .. 1;}; -- Error?
		hostB: processor {Priority_Range => 1 .. 32;};		
		app: process Aproc.Imp;
	properties
		Actual_Processor_Binding => (reference(hostB)) applies to app, app.task;
		Priority => 33 applies to app.task; -- Error?
	end ASys.Imp;
	
end RangeOrder;

**Comment by klreamsei** [comment]
First part dealing with lower range being greater than upper was fixed in commit 5fc1dbea6c69c90bac38650358bd76acacc7d2dd as part of fix for #566.  The 2nd part must be fixed in instantiation because binding needs to be resolved and instance model generation time.

**Comment by lwrage** [comment]
Maybe this check can be done using Resolute.

**Comment by klreamsei** [comment]
Remaining work related to #582
