### ISSUE TITLE
GIT Timeout When Installing OSATE 2.1.0 Source Files

### ISSUE THREAD

**Issue by spmiller2055** [osate/osate2-core#586]
When installing the OSATE source files from my local clone of  https://github.com/osate/development.git as described on the Getting OSATE 2 Sources Wiki

------------------------
Getting the sources of Osate 2

This assumes that you have cloned the repository [6] to your machine.
Import all osate sources: File -> Import -> Team -> Team Project Set -> select file "osate2.psf" from the cloned development git repository -> Open -> Finish -> (wait)
--------------------------

I get a "Connection time out: github.com" error.

**Comment by lwrage** [comment]
This is some kind of network issue with accessing github. There's nothing we can do about it. We have seen this sporadically but it was never permanent.

**Comment by spmiller2055** [comment]
I rebooted my machine, deleted the clone repository, recreated it and everything worked.
