### ISSUE TITLE
Broken Icons

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2-core#591]
This is related to #548. Posting a new issue since I can't reopen the issue.

The graphical editor was modified to use the directory specified in #548. However, somewhere in the process of consolidating things, many of the icons were replaced with generic icons. I believe that occured in cbae871. As a result the icons used by the graphical editor are no longer correct in OSATE 2.1.0 .

I have attempted to make a list of the incorrect icons. Can you please revert the changes to the following icons:

AbstractType
AbstractImplementation
AbstractFeature
AccessConnection
FeatureConnection
PortConnection
SubprogramAccess
SubprogramCallSequence
SubprogramGroupAccess
SubprogramGroupType
SubprogramGroupImplementation
SubprogramGroupSubcomponent

**Comment by lwrage** [comment]
Ken, if you look at cbae871268139da3c0e1661729b26bd8e01f1bd2 in a browser you see all the images that were replaced.
