### ISSUE TITLE
Validation of "passthrough" connections in newer versions of OSATE

### ISSUE THREAD

**Issue by backesj** [osate/osate2-core#592]
The following model validated correctly in past versions of the tool, but now longer validates in OSATE 2.1.0:

```
system test_sys
  features
    pass_a : in out data port;
    pass_b : in out data port;
end test_sys;

system implementation test_sys.i
  connections
    passthrough : port pass_a <-> pass_b;
end test_sys.i;
```

OSATE reports the following error:

`Illegal connection: Cannot directly connect two features of the containing component.`

It seems to me that you may want to express connections in a model that are simply "passed through" a component interface. For example, if you have two interfaces on some hardware component that are literally hard-wired to each other.  Why is this no longer valid?

**Comment by reteprelief** [comment]
If you are interested in specifying that a certain input to test_sys flows to a certain output you want to use the flow path specification.

Connection are intended to specify connectivity between components. If you are saying that test_sys is just passing through the input, would that mean that it does not process it, i.e., there will not be any subcomponent within test_sys involved in processing the data?

**Comment by backesj** [comment]
>
> If you are saying that test_sys is just passing through the input, would
> that mean that it does not process it, i.e., there will not be any
> subcomponent within test_sys involved in processing the data?


Yeah that's correct. I'm trying to model how some devices (Integrated
Circuits) are connected to each other on a printed circuit board. The board
has interfaces (headers) and the pins on the headers are hard wired to some
devices. However, some of the pins between interfaces are hard wired to
each other (the don't go through any devices). Does it make sense to model
these with a flow since they don't go through any components? On the other
hand, there really is a connection between the interfaces. What is the
correct way of representing this?

**Comment by reteprelief** [comment]
If I understand you correctly, the incoming hardware pin is directly wired to the outgoing hardware pin without any signals going through the device. In other words, the device if effectively not there.

**Comment by backesj** [comment]
Yes. However, the interfaces are modeled as feature groups, and there are
pins on the feature groups that do connect to devices. Here is the exact
example where I ran into the problem:

```
system XU_DAUGHTER_BOARD
  features
    ide : feature group Odroid_IDE_Interface;
    mpi : feature group Odroid_MIPI_Interface;
    exp : feature group Expansion_Slot;
    can : requires bus access hardware_types::CAN;
end XU_DAUGHTER_BOARD;

system implementation XU_DAUGHTER_BOARD.i
  subcomponents
    mpu_dev : device MPU;
    gyro : device Gyroscope;
    baro : device Barometer;
    accel : device Accelerometer;
  connections
    mpu_spi : bus access ide.SPI_1 <-> mpu_dev.spi;
    gyro_spi : bus access ide.SPI_1 <-> gyro.spi;
    baro_spi : bus access ide.SPI_1 <-> baro.spi;
    accel_spi : bus access ide.SPI_1 <-> accel.spi;
    uart_0_uart_ext : port ide.UART_0 <-> exp.UART_EXT;

end XU_DAUGHTER_BOARD.i;
```

I get the syntax error on the last connection.

**Comment by lwrage** [comment]
This is a language issue and should be discussed on saeaadl/aadlv2.2 or saeaadl/aadlv3

Also, implementing support for this kind of connection would require major rework of connection and flow instantiation.
