### ISSUE TITLE
Flow Path editing Bug

### ISSUE THREAD

**Issue by Korny666** [osate/osate2-core#598]
In the file deviceDefinition.aadl at line 106 are two end to end flows defined.
I added them via the Gui. I could maintain and change them via the gui until i set "in modes (...)".
Before i set the modes in the textual layout i got the following error: [Multiple markers at this line
 'logicThreadServer' does not exist in mode 'unknown'. - 'logicThreadServer' does not exist in mode 'client'.]. After i put in the modes via the gui or the textual representation, the textual error where gone, but the editing Wizard for the flows will not show up in the diagramm playerProcess.impl.
So did i something wrong? It is a bug? I have the following Osate-Eclipse

AADL-BA-FrontEnd				1.0.0.v20150216-1636	org.osate.ba.feature.feature.group	TELECOM ParisTech
AADL-Utils						1.0.0.v20141117-0906	org.osate.utils.feature.feature.group	TELECOM ParisTech
Agree							1.0.0.v20150224-1902	com.rockwellcollins.atc.agree.feature.feature.group	ROCKWELLCOLLINS
CertWare OMG SACM				1.1.0.201504241042		net.certware.feature.sacm.feature.group	Kestrel Technology LLC
Error Model Annex V2 for OSATE2	2.1.0.v20150422-1956	org.osate.xtext.aadl2.errormodel.feature.feature.group	CMU-SEI
OSATE2							2.1.0.v20150501-1818	osate2	null
OSATE2-Ocarina					0.0.1.v20150331-1301	org.osate.ocarina.feature.feature.group	null
Resolute						1.0.0.v20150410-0041	com.rockwellcollins.atc.resolute.feature.feature.group	ROCKWELLCOLLINS

	package deviceDefinition
	public
		system player
		end player;
	
		device speaker
			features
				soundWave: in event port;
		end speaker;
	
		device networkcontroller
			features
				new_feature: requires bus access networkCommunication;
		end networkcontroller;
	
		device soundcard
			features
				analogOut: out event port;
				inInterface: feature group inverse of soundStreamInterface;
			flows
				digitalToAnalog: flow path inInterface.newSoundStreamData -> analogOut;
		end soundcard;
	
		system implementation player.impl
			subcomponents
				network: device networkcontroller;
				soundcard: device soundcard;
				speakerLeft: device speaker;
	
				new_subcomponent: process playerProcess.impl;
				new_subcomponent2: device userInputDevice;
			connections
				wire: feature soundcard.analogOut -> speakerLeft.soundWave;
				UserInput: feature new_subcomponent2.outputFromUser -> new_subcomponent.inInterface;
				soundStream: feature new_subcomponent.outInterfaceServer -> soundcard.inInterface;
				networkCommunication: feature network.new_feature <-> new_subcomponent.inInterfaceClient;
		end player.impl;
	
		data soundStream
		end soundStream;
	
		process playerProcess
			features
				inInterface: feature group userInputInterface;
				outInterfaceServer: feature group inverse of soundStreamInterface;
				inInterfaceClient: feature group soundStreamInterface;
		end playerProcess;
	
		thread uiThread
			features
				outAndInInterface: in out event data port userInput;
				inInterface: feature group userInputInterface;
			flows
				newUserInputSource: flow source inInterface.newUserInput;
				displayNewStateSink: flow sink outAndInInterface;
			modes
				showPlaying: mode;
				showPause: initial mode;
				displayNowPlayingFromUserInput: showPause -[inInterface.newUserInput]-> showPlaying;
				displayNowPlayingFromServerInput: showPause -[outAndInInterface]-> showPlaying;
				displayNowPauseFromUserInput: showPlaying -[inInterface.newUserInput]-> showPause;
				displayNowPauseFromServerInput: showPlaying -[outAndInInterface]-> showPause;
		end uiThread;
	
		thread logicThreadServer
			features
				fromAndToUi: in out event data port userInput;
				outInterface: feature group soundStreamInterface;
			flows
				userInputSink: flow sink fromAndToUi;
				soundStreamFlowSource: flow source outInterface.newSoundStreamData;
			modes
				playing: mode;
				pause: initial mode;
				nowPlaying: pause -[fromAndToUi]-> playing;
				nowPause: playing -[fromAndToUi]-> pause;
		end logicThreadServer;
	
		thread logicThreadClient
			features
				fromAndToUi: in out event data port userInput;
				inInterface: feature group inverse of soundStreamInterface;
				outInterface: feature group soundStreamInterface;
			flows
				uiSource: flow source fromAndToUi;
				nowShowPlaying: flow path inInterface.metaInformation -> fromAndToUi;
				soundStream: flow path inInterface.newSoundStreamData -> outInterface.newSoundStreamData;
			modes
				playing: mode;
				pause: initial mode;
				newData: pause -[inInterface.newSoundStreamData]-> playing;
		end logicThreadClient;
	
		process implementation playerProcess.impl
			subcomponents
				uiThread: thread uiThread.impl in modes (server, client);
				logicThreadServer: thread logicThreadServer.impl in modes (server);
				logicThreadClient: thread logicThreadClient.impl in modes (client);
	
			connections
				newUserInput: feature uiThread.inInterface -> logicThreadServer.fromAndToUi in modes (server);
				newSoundStreamFromInternalPlayer: feature logicThreadServer.outInterface -> outInterfaceServer in modes (server);
				newSoundDataFromServer: feature inInterfaceClient -> logicThreadClient.inInterface in modes (client);
				newSoundStreamFromServer: feature logicThreadClient.outInterface -> outInterfaceServer in modes (client);
				showState: port logicThreadClient.fromAndToUi -> uiThread.outAndInInterface in modes (client);
			flows
				processNewUserInputFlow: end to end flow uiThread.newUserInputSource -> newUserInput ->
						logicThreadServer.userInputSink in modes (server);
				displayNewStateAndInformationClientFlow: end to end flow logicThreadClient.uiSource -> showState ->
						uiThread.displayNewStateSink in modes (client);
			modes
				server: mode;
				client: mode;
				unknown: initial mode;
				workAsAServer: unknown -[inInterface.newUserInput]-> server;
				workAsAClient: unknown -[inInterface.newUserInput]-> client;
		end playerProcess.impl;
	
		bus networkCommunication
		end networkCommunication;
	
		feature group userInputInterface
			features
				newUserInput: out event data port userInput;
		end userInputInterface;
	
		data userInput
		end userInput;
	
		feature group soundStreamInterface
			features
				newSoundStreamData: out event data port soundStream;
				metaInformation: in out parameter;
		end soundStreamInterface;
	
		thread implementation uiThread.impl
		end uiThread.impl;
	
		thread implementation logicThreadServer.impl
		end logicThreadServer.impl;
	
		thread implementation logicThreadClient.impl
		end logicThreadClient.impl;
	
		bus speakerCable
		end speakerCable;
	
		device userInputDevice
			features
				inputFromUser: in event port;
	
				outputFromUser: feature group userInputInterface;
			flows
				newUserInput: flow source outputFromUser.newUserInput;
				newKeyOrWhaterver: flow path inputFromUser -> outputFromUser.newUserInput;
		end userInputDevice;
	
	end deviceDefinition;

**Comment by philip-alldredge** [comment]
The issue is triggered by EcoreUtil.copy being called on an end to end flow when that flow references a mode in its in modes clause. 

The root cause appears to be that the inModes feature is being reported as changeable and not derived. The exception is triggered when the EcoreUtil class tries to copy the inMode reference and ModalPathOperations.getInModes doesn't return a list that implements the appropriate interfaces for a changeable feature. 

I think the ideal way to solve the problem is to fix it at the meta model level so that EcoreUtil will work properly in this case. 

@lwrage is that something that is practical in this case? My understanding based on looking at the metamodel is that the intention is that inModes is changeable in ModalElement but isn't supposed to be in ModalPath.

**Comment by philip-alldredge** [comment]
@lwrage Do you have any thoughts on this issue?

**Comment by philip-alldredge** [comment]
Any thoughts on the best way to get this fixed?

**Comment by Korny666** [comment]
Sry-no i got no deeper Look into OSATE/AADL/Equinox Development.
Couldn't you reproduce it?

**Comment by philip-alldredge** [comment]
Sorry, my comment was directed at the OSATE2-core developers. I could reproduce it but as detailed in my comments, it appears from my perspective to be an issue with the osate2-core rather than the graphical editor.

**Comment by lwrage** [comment]
I'll try to have a look at the issue next week.

**Comment by lwrage** [comment]
This bug is caused by a limitation in the UML to Ecore conversion. ModalPath redefines property inMode as derived, this is fine in UML but the information does not make it into the Ecore model, so EMF treats it as changeable. I tried to work around this by fiddling with the generated code but it can't really be fixed there. Eliminating the redefinition would break existing code in the instantiation.

I think for now the flow editing dialog should just not handle modal flows and give the user a warning. 

The redefinition in the metamodel is really a hack to work around the fact that the in modes clause for connections, and flows mixes modes and mode transitions. The best fix would probably be a language improvement to write modal paths as `name: ... in modes (<mode names>) in transitions (<mode transition names>);`

**Comment by philip-alldredge** [comment]
Okay. Thanks for tracking things down. We'll look into implementing the described workaround during the current development effort.

**Comment by philip-alldredge** [comment]
A workaround has been pushed to the graphical editor. The workaround copies flows which have an in modes clause manually. This works around the problem with using EcoreUtil.copy. The editor show now work correctly with such flows.

Please use the osate-ge issue tracker for future issues. https://github.com/osate/osate-ge/issues
