### ISSUE TITLE
When having a "Naked" Workspace Wizard - Bug

### ISSUE THREAD

**Issue by Korny666** [osate/osate2-core#599]
Then you should only be able to create a new Aadl Project - nothing else (ends up in a npe)

**Comment by klreamsei** [comment]
Can you clarify steps to reproduce this, please?

**Comment by Korny666** [comment]
new workspace in your osate eclipse (so nothing is in it) not a single Project.
There are then displayed 3 aadl-wizards so there MUST be only the project wizard. (last one)
The other two Aadl Model and Aadl Graphical Package MUST NOT be there ;)
