### ISSUE TITLE
Xtext cross-reference to SubprogramAccess

### ISSUE THREAD

**Issue by brlarson** [osate/osate2-core#607]
I'm unsure whether this is a bug, but I'll record it here anyway.  My Xtext-based annex sublanguage parser puts error markers on subprogram invocations with the message:  
"Couldn't resolve reference to Subprogram Access 'ActuatorCommand'"
I'm trying to cross-reference core language objects whenever they're used.  Xtext grammar:

SubprogramCall returns SubprogramCall:
  procedure=[aadl2::SubprogramAccess] '(' parameters=FormalActualList? ')' ;

The text getting marker is:  "ActuatorCommand(pc:0)"
This is in an annex subclause of an implementation of a type with has:

features
	ActuatorCommand: refined to requires subprogram access MI::Fragile;   

I'd expect that the cross reference would find the feature in its type.
Of course I can make the markers go away by changing [aadl2::SubprogramAccess] to ID, but the cross references to ports and properties work great, and I'd like to include subprogram access features too.

Reproducing the error would require running my plug-in(s) with the whole stepper motor project, which is impractical.  To remove the annoyance I'm taking out the cross-references to SubprogramAccess, but any suggestions will be welcome.

**Comment by lwrage** [comment]
I would guess that the scope for that reference is incomplete. You can see which names are in the scope when you use content assist in the text editor.

**Comment by lwrage** [comment]
Not a bug in OSATE
