### ISSUE TITLE
Deadlock when editing file with annex errors with 'AADL Navigator' and 'Outline' open

### ISSUE THREAD

**Issue by agacek** [osate/osate2-core#611]
To create the deadlock:

1. Open the AADL perspective in OSATE.
2. Create a project with this AADL file:

    package Bug
    public
      thread Bug   
        annex behavior_specification {**    
          variables
            x: Base_Types::Integer;
            y: Base_Types::Integer;  
          states
            a :  state ;
            b :  state ;
            c :  state 
            d :  state ;
            e :  state ;
            f :  state ;
    **};
      end Bug;
    end Bug;

2. Ensure the 'AADL Naviagtor' view is open with the Bug.aadl file visible in it
3. Ensure the 'Outline' view is open with the Bug package visible in it
4. Make some trivial changes and edits to Bug.aadl
5. OSATE should deadlock

The bug was introduced in commit dd7e47340d972da0d3ccd5963599752ac9e56681.

**Comment by lwrage** [comment]
The solution is a workaround. There is some underlying issue w.r.t. error markers that needs to be investigated.
