### ISSUE TITLE
Flow Sink Implementation Serialization

### ISSUE THREAD

**Issue by RyanMcilnay** [osate/osate2-core#617]
I have the following package:
<hr>
	package flow_sink_sc_serialization_bug
	public
		system top
		features
			in1 : in data port;		
		flows
			fsnk1: flow sink in1;
	end top;
	
	system bottom
	features
		in1 : in data port;
	end bottom;
	
	system implementation top.impl
	subcomponents
		sc1 : system bottom;
		
	connections
			c1: port in1 -> sc1.in1;

	flows
			fsnk1: flow sink in1 -> c1 -> sc1;
	end top.impl;
	end flow_sink_sc_serialization_bug;
<hr>

When I save the package as XMI, then select Save Model (aaxl2) As Text (aadl), 
the fsnk1: flow implementation is now:

	fsnk1: flow sink c1 -> sc1 -> in1;

**Comment by lwrage** [comment]
The flow sink is serialized as a flow source. The Xtext serializer gets confused, maybe because the grammar is not LL(1).
