### ISSUE TITLE
Issue with getSizesForSubcomponents in Aadl2JavaValidator.java

### ISSUE THREAD

**Issue by juli1** [osate/osate2-core#622]
In Aadl2JavaValidator , there is the following error which then makes the compilation process to fail.

Type mismatch: cannot convert from Stream<Object> to Stream<Optional<Aadl2JavaValidator.LongWithUnits>>	Aadl2JavaValidator.java	/org.osate.xtext.aadl2/src/org/osate/xtext/aadl2/validation	line 3587	Java Problem

**Comment by joeseibel** [comment]
It compiles fine for me.  Do you have any errors in the imports section of the file?

**Comment by juli1** [comment]
Nop, no error on that front. What version of eclipse and xtext are you using?
I am using Eclipse mars with xtext 2.8.4

**Comment by lwrage** [comment]
Osate is still on Luna.

**Comment by juli1** [comment]
The following patch solves the issue (but there are still some warnings).

diff --git a/org.osate.xtext.aadl2/src/org/osate/xtext/aadl2/validation/Aadl2JavaValidator.java b/org.osate.xtext.aadl2/src/org/osate/xtext/aadl2/validation/Aadl2JavaValidator.java
index b962369..8dbc324 100644
--- a/org.osate.xtext.aadl2/src/org/osate/xtext/aadl2/validation/Aadl2JavaValidator.java
+++ b/org.osate.xtext.aadl2/src/org/osate/xtext/aadl2/validation/Aadl2JavaValidator.java
@@ -3564,7 +3564,7 @@
 		Property dataSizeProperty = GetProperties.lookupPropertyDefinition(dataImplementation, MemoryProperties._NAME, MemoryProperties.SOURCE_DATA_SIZE);
 		try {
 			LongWithUnits implementationSize = new LongWithUnits((IntegerLiteral)PropertyUtils.getSimplePropertyValue(dataImplementation, dataSizeProperty));
-			List<Optional<LongWithUnits>> subcomponentSizes = getSizesForSubcomponents(dataImplementation, dataSizeProperty).collect(Collectors.toList());
+			List<Optional<LongWithUnits>> subcomponentSizes = (List<Optional<LongWithUnits>>) getSizesForSubcomponents(dataImplementation, dataSizeProperty).collect(Collectors.toList());
 			Optional<LongWithUnits> optionalSum = subcomponentSizes.stream().filter(subcomponentSize -> subcomponentSize.isPresent()).map(subcomponentSize -> subcomponentSize.get()).reduce((a, b) -> a.add(b));
 			if (optionalSum.isPresent()) {
 				LongWithUnits sum = optionalSum.get();
@@ -3583,7 +3583,7 @@
 		}
 	}
 	
-	private static Stream<Optional<LongWithUnits>> getSizesForSubcomponents(DataImplementation dataImplementation, Property dataSizeProperty) {
+	private static Stream getSizesForSubcomponents(DataImplementation dataImplementation, Property dataSizeProperty) {
 		return dataImplementation.getAllSubcomponents().stream().filter(subcomponent -> subcomponent instanceof DataSubcomponent).flatMap(dataSubcomponent -> {
 			try {
 				return Stream.of(Optional.of(new LongWithUnits((IntegerLiteral)PropertyUtils.getSimplePropertyValue(dataSubcomponent, dataSizeProperty))));

**Comment by juli1** [comment]
Ok, copy/paste the patch was a miserable failure. There is the corresponding gist

https://gist.github.com/juli1/c11535387f1b726f1310

**Comment by juli1** [comment]
Fixed, thanks to Joe!
