### ISSUE TITLE
keyword/construct completion bug for component blocks

### ISSUE THREAD

**Issue by Welchd1** [osate/osate2-core#628]
Hi, not sure if I'm posting this in the right place (and I'm not even totally sure you'd classify this as a bug),
but it's kind of annoying when you have something something like this already typed in:

```
abstract implementation some_other_system.impl
end some_other_system.impl; 
```
then you get to the point where you want to add, say, a subcomponent to this.. So you put your cursor after `some_other_system.impl`, hit return, and boom you automatically end up with something like this (thanks to the construct's live template .. or whatever xtext is doing):
```
abstract implementation some_other_system.impl
end some_other_system.impl; 
end some_other_system.impl; 
```

like I said, it's a small thing but still occasionally trips me up.

**Comment by reteprelief** [comment]
Ken,
it only happens when the cursor in the same line as the .impl name. 
It does not happen when the cursor is at the beginning of the next line.
Also it seems to be affected by how the name is written.
It does not do it when the cursor is after peter, but it does when it is after SensorData.
If you replace peter by PeterFeiler it will add the end when you put the cursor after PeterFeiler and hit enter.
package format
public
	data peter
		properties
			Data_Size => 2 KByte; 
	end peter;
	data SensorData
		properties
			Data_Size => 2 KByte; 
	end SensorData;

end format;

**Comment by klreamsei** [comment]
I was able to replicate and have a fix for Peter's example which was caused  by a string comparison needing to ignore case. However, the original posted example I couldn't replicate with the example given. Have you actually tried "some_other_system.impl" or is that a placeholder example? In Peter's example, it failed if there was some capitalization in the name. I'll continue to investigate and see if I can replicate this.

**Comment by Welchd1** [comment]
you're absolutely right, it actually works for the case I posted (sigh) -- that was just a bad example. In reality I was typing this:

```
abstract implementation TrafficInfoCenter.impl
end TrafficInfoCenter.impl
```

And that would add the extra `end...` if I pressed enter after the first `impl`. I guess it's because the name contained capitals.
