### ISSUE TITLE
Indentation is forced

### ISSUE THREAD

**Issue by juli1** [osate/osate2-core#630]
Hi,

It would be nice to not having the indentation forced all the time. For example, if I type the name of a component, I type enter, a tab is added. If I decided to remove the tab manually, type features and then enter, the tab is added ***again***. This is very annoying. Having the ability to automatically add/remove auto-indentation would be great. Also, having a specific style would be helpful, with the current rules, we ended having three/fours tab nesting levels, which is clearly too much for a descriptive language.

**Comment by klreamsei** [comment]
Have you tried changing the Aadl2 Text Editor Preferences under Osate Preferences? Turning off "Automatically set indent of component section keywords" should stop exactly what you describe.  Turning off "AutoIndent next line after keywords" might also be helpful to you.

**Comment by juli1** [comment]
You rock! You made my day! Thank you so much!
