### ISSUE TITLE
NullpointerException on Instantiation

### ISSUE THREAD

**Issue by Korny666** [osate/osate2-core#638]
Here is the commit and line: https://github.com/osate/osate2-core/commit/adeb9359ef3835bb6026173271c7152a333668b6

should there be a null check? -> got a npe for ic.bindings.isEmpty

I know this is wrong, but a npe should not happen. -> instantiate process implementation main.impl

package project_module
public
	with Base_Types;

	feature group SetAndGetInteger
		features
			setValue: in data port Base_Types::Integer;
			getValue: out data port Base_Types::Integer;
	end SetAndGetInteger;

	thread CounterThread
		features
			setterAndGetter: feature group SetAndGetInteger;
			count: in event port;
			reset: in event port;
		modes
			untouched: initial mode;
			counter_was_triggerd: mode;
			realize_first_count: untouched -[count]-> counter_was_triggerd;
			back_to_untouched: counter_was_triggerd -[reset]-> untouched;
	end CounterThread;

	thread implementation CounterThread.impl
		subcomponents
			CounterDataValue: data Base_Types::Integer;
		connections
			set_new_value: parameter setterAndGetter.setValue -> CounterDataValue;
			return_count: parameter CounterDataValue -> setterAndGetter.getValue;
		properties
			Priority => 1;
	end CounterThread.impl;

	process main
	end main;

	process implementation main.impl
		subcomponents
			counterThread: thread CounterThread.impl;
	end main.impl;

end project_module;

**Comment by lwrage** [comment]
Was already fixed
