### ISSUE TITLE
Error with a connection instance associated with several buses

### ISSUE THREAD

**Issue by juli1** [osate/osate2-core#649]
When a connection instance has sub-connections associated with different buses, instantiating the model reports errors. 
To reproduce:
- Checkout the project https://github.com/osate/examples/tree/master/iot-example
- Instantiate the system implementation iot_system.complete several instantiation errors will be reported.

One suggestion would be to associate the property to the connection instance if the property value is consistent along the connections or just let the properties associated with just the sub connection. It might impact existing analysis plugins.

**Comment by lwrage** [comment]
The IOT example is not a valid AADL project. The `.project` file is missing. BTW, what do you mean by sub-connection?
