### ISSUE TITLE
Refining a bi-directional connection looses one direction in the instance file.

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2-core#662]
-- Refinement of two-way connection causes loss of one direction.
-- This was observed in version 2.1.0 and 2.2.0.
```
package RefineFeatureConnection
public
	
	system AbstractWorkload
		features
			groupOut: feature;
			groupIn: feature;
	end AbstractWorkload;
	
	system Errata
	end Errata;
	
	-- Look at the instance file for this system.  There
	-- will be 4 connections, a pair for each of the declared
	-- connections, each pair being a connection in one
	-- direction and a connection in the other.
	system implementation Errata.AbstractFeatures
	subcomponents
		work1: system AbstractWorkload;
		work2: system AbstractWorkload;
		platform: system;
	connections
		fg_con1: feature work1.groupOut <-> work2.groupIn;
		fg_con2: feature work1.groupIn <-> work2.groupOut;
	properties
		Actual_Processor_Binding => (reference (platform)) applies to work1, work2;
		Actual_Memory_Binding => (reference (platform)) applies to work1, work2;
		Actual_Connection_Binding => (reference (platform))	applies to fg_con1, fg_con2;	
	end Errata.AbstractFeatures;
	
	-- Look at the instance file for this system.  There
	-- are only 3 connections.  Refining the fg_con1 connection
	-- causes one of the pair of one-way connections to be
	-- omitted.
	system implementation Errata.Refinement extends Errata.AbstractFeatures
	connections
		fg_con1: refined to feature;		
	end Errata.Refinement;	
	
end RefineFeatureConnection;
```

**Comment by lwrage** [comment]
Do you know if this occurs only with feature group connections or also with other connections?

**Comment by stevevestal** [comment]
This occurred with connections between abstract features.  I haven't
    tried it with feature group or other kinds of connections.
    
    On 1/9/2016 9:52 AM, Lutz Wrage wrote:
    
    
      Do you know if this occurs only with feature group connections or also with other connections?

---
Reply to this email directly or view it on GitHub:
https://github.com/osate/osate2-core/issues/662#issuecomment-170254268
      
      
      
      Do you know if this occurs only with feature group connections
        or also with other connections?
      —
        Reply to this email directly or view
          it on GitHub.
