### ISSUE TITLE
Access connection instance claims component to component

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2-core#672]
We have a bus and a system that contains a subsystem. The subsystem requires bus access via the system interface. If the connection declaration within the system to the subsystem is declared as
subsystem.accessfeature <-> accessfeature we get an error message on instantiation about connecting a component to a component.

```
package BusAccess
public

device Stepper_Motor
features
    Power: requires bus access Power_Supply;
end Stepper_Motor;

bus Power_Supply
end Power_Supply;

system SMS
features
    Power: requires bus access Power_Supply;
end SMS;

system implementation SMS.Original
subcomponents
    SM_Motor: device Stepper_Motor;
connections
    PowerToSM: bus access  SM_Motor.power <-> Power; 
end SMS.Original;


system top
end top;

system implementation top.original
subcomponents
    SMS: system SMS.original;
    Powersupply: bus Power_Supply;
connections
    pwrpcs: bus access Powersupply <-> SMS.Power;
end top.original;

end BusAccess ;
```

**Comment by lwrage** [comment]
I cannot reproduce this using the develop branch. @reteprelief Could you check if this is still an issue?

**Comment by lwrage** [comment]
@reteprelief Please reopen if this is still an issue
