### ISSUE TITLE
Flow Specifications and Feature Arrays

### ISSUE THREAD

**Issue by joeseibel** [osate/osate2-core#678]
The syntax of flow specifications does not allow an index to be specified when referring to a feature array.  Also, when a flow does refer to a feature array, it is not clear how this should be instantiated.  For example, what does it mean when the source and destination features of a flow specification are arrays of different sizes?  How should this model be instantiated:

```
system s
features
  p1: in data port[4];
  p2: out data port[3];
flows
  f1: flow path p1 -> p2;
  f2: flow sink p1;
end s;
```

**Comment by lwrage** [comment]
This is a language issue and should be discussed on saeaadl/aadlv2.2 or saeaadl/aadlv3
