### ISSUE TITLE
Xtext AADL qualified name provider should provide names for features, subcomponents and flows

### ISSUE THREAD

**Issue by dblouin** [osate/osate2-core#680]
Right now, names will be only provided for AadlPackage, Classifier, PropertyConstant, Property, PropertySet, PropertyType and PackageSection. Refined feature and subcomponent should be testes as well.

**Comment by lwrage** [comment]
This would not be a good idea. If something has a qualified name Xtext treats it as globally visible and puts it in the global scope. This would slow down name resolution, etc. In Xtext tt is recommended to keep local names out of the global scope.
