### ISSUE TITLE
Self-connections appear in instance files

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2-core#682]
In a model with a connection of the form a.b <-> c.d, version 2.2 now sometimes creates a pair of connections
a.b -> a.b
c.d -> a.b
where the bidirectional property is false for both.

I looked at a version 2.1 instance file, and the same model caused a single connection to appear,
a.b -> c.d
where the bidirectional property is true.

Is this a known and intentional change in the instance file?  The 2.1 version sort of makes more intuitive sense (and avoids breaking legacy plugins).

**Comment by lwrage** [comment]
I don't think there was an intentional change. Please provide a (small) example model that shows the different behavior so we can investigate.

**Comment by lwrage** [comment]
Fixed with #681
