### ISSUE TITLE
OSATE does not use the Classifier Matching Rule on feature connections

### ISSUE THREAD

**Issue by blavalley** [osate/osate2-core#703]
The Classifier Matching Rule property used to subset a feature groups and split it into several feature groups connections on sub components  is not used in OSATE when the instance model is generated. Able to get  clean syntax in the OSATE editor when specifying the property but when the model is instantiated a pop up warning is shown and the instantiation fails.  There pop up says:
>  "Error when instantiating the model - reason: assertion failed:
> Connected feature groups so not have the same number of features"

It is correct that the number of features do not match but the AADL documentation indicates that the Classifier Matching Rule => Subset should handle this.

Attached is a sample that generates the error.  I am using AADL OSATE 2.2.0, on Eclipse 4.5.2 under Windows 10.
[fgst.txt](https://github.com/osate/osate2-core/files/234918/fgst.txt)

**Comment by lwrage** [comment]
Support for classifier matching rule and similar properties is not implemented for instantiation.

**Comment by blavalley** [comment]
Yes, I talked with Peter Feiler and he thought that was the case.  I am working to get a major prime to adopt AADL for interface specification and this would be a really useful feature.  Is there a way that this could get implemented?
