### ISSUE TITLE
Example Projects Appear to be Empty

### ISSUE THREAD

**Issue by brlarson** [osate/osate2-core#704]
With 2.2.1 I tried to create example AADL projects (arinc, arincexample1, AircraftSubsystems) a project appears, but has nothing in it.

**Comment by lwrage** [comment]
I tried with a fresh install and it works just fine. Tested on Win 7 and OSX.

**Comment by brlarson** [comment]
This time it worked great.  

I needed to double-click available projects on the l.h.s. to make them appear on the right.

I don't recall seeing them at all before.  Perhaps it's just old age!
