### ISSUE TITLE
Add Graphiti Export Plugin to Releases

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2-core#707]
It was recently pointed out that it is not possible to export a graphical diagram as SVG. This is caused by the Graphiti Export Plugin (Incubation) not being included in the OSATE releases.

Currently, the user must manually install the plugin using the following steps:
Install the Modeling->Graphiti Export (Incubation) from the eclipse update site.

@yoogx

**Comment by yoogx** [comment]
for some reasons I add to install this dependence manually for OSATE 2.2.1 on Mac. Is it expected ? When installed, the export to SVG is working as expected

**Comment by lwrage** [comment]
This is expected. The exporter was added to OSATE in May 2016, OSATE 2.2.1 is from April 2016. I think the exporter is optional, so updating the existing installation will not install it automatically. It's been part of the full installation since 2.2.1-01.
