### ISSUE TITLE
Unused ErrorLibrary import causes error instead of warning

### ISSUE THREAD

**Issue by brlarson** [osate/osate2-core#708]
example:

  with
    Base_Types, 
    EMV2, 
    ErrorLibrary,
    Physical_Types,

For EMV2 (also unused in this package) get warning, 
for ErrorLibrary get error:

Description	Resource	Path	Location	Type
Couldn't resolve reference to ModelUnit 'ErrorLibrary'.	PCA_Fluid.aadl	/PCA/aadl/packages	line: 10 /PCA/aadl/packages/PCA_Fluid.aadl	Xtext Check (fast)

**Comment by lwrage** [comment]
This should be fixed already in the testing version.

**Comment by brlarson** [comment]
Okay.

I've been going back and forth to be sure the BLESS plug-ins work with 2.2.1.

--Brian

**Comment by reteprelief** [comment]
Fixed by osate/ErrorModelV2#105
