### ISSUE TITLE
Add experimental "physical" feature

### ISSUE THREAD

**Issue by brlarson** [osate/osate2-core#713]
Please add "physical" feature to experimental (v3) version of OSATE.

Currently revising Open PCA Pump model, and would like to make the drug connections "physical" rather than "data".  Making them "abstract" instead suggests the features will be refined at some later point, rather than already known to be liquid.

Consider allowing "physical" classifier too, to define the type of physical features.

A "Physical_Characteristics" property set would define physical attributes, and be included in the unified type/unit relations system.

But just allowing "physical" feature for now would be great.

**Comment by lwrage** [comment]
We won't implement that in OSATE unless the committee decides to add physical features to the language. 

Maybe, as a workaround, you could use an empty feature group type named "Physical" instead of abstract features?
