### ISSUE TITLE
with ErrorLibrary; causes couldn't resolve reference error

### ISSUE THREAD

**Issue by brlarson** [osate/osate2-core#716]
package Generic_Voter
public
	with ErrorLibrary; 
 . . .

causes error:

Couldn't resolve reference to ModelUnit 'ErrorLibrary'.	Generic_Voter.aadl	/ReplicationExperiment/packages	line: 3 /ReplicationExperiment/packages/Generic_Voter.aadl	Xtext Check (fast)

However, it's found as built-in, pre-declared property set in
  annex EMV2
  {**
  	use types ErrorLibrary;

**Comment by reteprelief** [comment]
Addressed by ErrorModelV2#105
Fix is in testing release and will be included in the 2.2.1 maintenance release coming out this week.
