### ISSUE TITLE
ARP4761 example project is empty

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2-core#738]
I just tried loading the ARP4761 example project using the Files -> Examples... sequence.  It created an empty project.

**Comment by lwrage** [comment]
I can't reproduce this. Did you double-click on the ARP4761 example in the wizard? Did it show up in the "Examples selected:" box? If not, an empty project is created.

**Comment by stevevestal** [comment]
OK, I was confused about the interface.  When I double-click on
      ARP4761 (rather than a single click and rather than on individual
      items listed under that heading) it does create the project.
    I get an error that HardwareFailure is undefined in one place,
      even after repeated Project->Clean, although it appears in
      other places in the model.
    
    
    On 10/6/2016 1:52 PM, Lutz Wrage wrote:
    
    
      I can't reproduce this. Did you double-click on the ARP4761 example in the wizard? Did it show up in the "Examples selected:" box? If not, an empty project is created.


      
      
      
      I can't reproduce this. Did you double-click on the ARP4761
        example in the wizard? Did it show up in the "Examples
        selected:" box? If not, an empty project is created.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/osate/osate2-core","title":"osate/osate2-core","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/osate/osate2-core"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lwrage in #738: I can't reproduce this. Did you double-click on the ARP4761 example in the wizard? Did it show up in the \"Examples selected:\" box? If not, an empty project is created."}],"action":{"name":"View Issue","url":"https://github.com/osate/osate2-core/issues/738#issuecomment-252055328"}}}
