### ISSUE TITLE
Data subcomponent connections

### ISSUE THREAD

**Issue by backesj** [osate/osate2-core#739]
This question is regarding what types of AADL connections between data implementations are considered valid. In the following model the connection "conn0" is validated by osate while "conn1" is not. What are the rules regarding connections to data subcomponents?

> package Test
> public
> 	with Base_Types;
> 	
> 	data Bar
> 	end Bar;
> 	
> 	data implementation Bar.i
> 		subcomponents
> 			a : data Base_Types::Integer;
> 	end Bar.i;
> 	
> 	data Foo
> 	end Foo;
> 	
> 	data implementation Foo.i
> 		subcomponents
> 			a : data Bar.i;
> 			b : data Base_Types::Integer;
> 	end Foo.i;
> 	
> 	
> 	system test
> 		features
> 			output: out data port Foo.i;
> 	end test;
> 	
> 	system sub
> 		features 
> 			output : out data port Base_Types::Integer;
> 	end sub;
> 	
> 	system implementation test.i
> 		subcomponents
> 			 sub : system sub;
> 		connections
> 			conn0 : port sub.output -> output.b;
> 			conn1 : port sub.output -> output.a.a;
> 	end test.i;
> 	
> 	
> end Test;

**Comment by lwrage** [comment]
The problem with conn1 is that the destination reaches too deep into the feature group. You can only go one level down. Rule of thumb: Use at most one dot in source and destination.

**Comment by backesj** [comment]
In this example I am not using a feature group. I am using a data implementation. I understand why you would allow connections to subfeatures in a feature group, but it seems strange that you would allow connections to subcomponents of a data implementation. Is this allowed in the standard? Or is this a validation bug in OSATE?

**Comment by lwrage** [comment]
Sorry for the confusion, I meant to write data component. You can not reach down multiple levels in either case.
Reaching one level into a data component is allowed. The standard calls that _aggregate data port_. OSATE validates the declarative connections with aggregate data ports correctly but cannot instantiate them (you get a null pointer exception).

**Comment by backesj** [comment]
Okay thanks!
