### ISSUE TITLE
Error instantiating model with aggregate data ports

### ISSUE THREAD

**Issue by backesj** [osate/osate2-core#744]
The following model produces an error when attempting to instantiate "test.i". The issue seems to be with handling connections where the destination is a data subcomponent.

```
package Test
public
  with Base_Types;

  data Bar
  end Bar;

  data implementation Bar.i
      subcomponents
          a : data Base_Types::Integer;
  end Bar.i;

  data Foo
  end Foo;

  data implementation Foo.i
      subcomponents
          a : data Bar.i;
          b : data Base_Types::Integer;
  end Foo.i;

  system test
      features
          output: out data port Foo.i;
  end test;

  system sub
      features 
          output : out data port Base_Types::Integer;
  end sub;

  system implementation test.i
      subcomponents
           sub : system sub;
      connections
          conn0 : port sub.output -> output.b;
  end test.i;

end Test;
```

**Comment by lwrage** [comment]
Aggregate data ports are not supported for instantiation. We'll should prevent instantiation of models containing aggregate data ports and issue a warning.

**Comment by backesj** [comment]
I see.

I was a bit confused by our conversation about this earlier. In previous
versions of OSATE you could instantiate models with aggregate data
connections.

- John

**Comment by lwrage** [comment]
I tried the instantiation with OSATE 2.2.1 final: Although the instantiation runs without reporting an error, the resulting instance model is not correct. The connections instance has no destination and has no connection reference to the connection in the declarative model.

**Comment by lwrage** [comment]
The validator now warns about aggregate data ports used in the declarative model. We don't prevent instantiation, but a warnings are added to the instance model if connections are not instantiated because they involve an aggregate data port.

**Comment by backesj** [comment]
This sounds like a good solution to me. Thanks!
