### ISSUE TITLE
Reference instantiated classifier from instance model

### ISSUE THREAD

**Issue by lwrage** [osate/osate2-core#746]
Component instances currently have a reference to the instantiated subcomponent in the declarative model. If the subcomponent's classifier is provided by a prototype actual it is difficult to find that classifer if it is needed by an analysis. For example, the error model analyses of an instance model access the emv2 annex in the declarative model. These analyses will not work correctly for model with prototypes. The issue also comes up when using a tool such as the design space explorer to fill in component implementations.
The fix would add a reference to a component classifier to component instances.

**Comment by brlarson** [comment]
This change is very important for Design Space Explorer to generate instance models that can be analyzed by tools that need properties in EMV2 annex subclauses.

**Comment by lwrage** [comment]
- [ ] add reference to instance metamodel
- [ ] fill reference during instantiation
- [ ] modify method that currently gets the classifier
- [ ] adapt textual instance model
