### ISSUE TITLE
formatting for connections

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2-core#754]
When adding a connection after the last connection, the formatter keeps adding a tab for additional indentation when I hit return, i.e., as I add connections they keep getting moved one tab to the right and I have to manually remove the tab. Annoying.
It does not do that if I insert a connection in the middle of a list of connection declarations when I hit a return there.

**Comment by lwrage** [comment]
I cannot reproduce this behavior.

**Comment by lwrage** [comment]
@reteprelief Please reopen if you can reproduce this.
