### ISSUE TITLE
Instantiating the behavior Annex PingPong example causes out of memory error

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2-core#756]
Trying to instantiate the example [MultiModalProducerConsumer](http://penelope.enst.fr/aadl/wiki/MultiModalProducerConsumer) from Telecom Paristech causes OSATE to max out its allocated heap and hang.

I increased the available heap to nearly 4GB and still it hung. Is this a bug, or does this example really just require a huge amount of ram?

![Observe the heap usage spike when I start the model instantiation](https://cloud.githubusercontent.com/assets/8142684/20754494/cb580e4a-b6d0-11e6-932d-31d45a89d13c.png)

I commented out the behavior annex portions of the model and still see similar behavior. 

I'm running:

> OSATE2	2.2.1.vupdate01

My `osate.ini`

```
-startup
plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.300.v20150602-1417
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Xms400m
-Xmx3768m
```

Java:

```
=> java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

=>javac -version
javac 1.8.0_101
```

**Comment by lwrage** [comment]
The model has 123 pingorpong.impl components, each with 3 modes, so we would end up with at least 3^123 SOMs in the instance model. See #666
