### ISSUE TITLE
Viewing data subcomponent properties on features

### ISSUE THREAD

**Issue by backesj** [osate/osate2-core#771]
The instance model seems to generate properties applied to the top level type of a feature. However, if the feature has subcomponents, these do not appear in the instance model. Likewise you cannot view properties assigned to these subcomponents. Consider the following example:

```
property set Test_Props is
	Test_Prop : aadlboolean applies to (all);
end Test_Props;
```

```
package Test 
public	 
	with Test_Props;

    data d1
    end d1;
    
    data d2
    end d2;
    
    data implementation d1.i
    	subcomponents
    		d2 : data d2 {Test_Props::Test_Prop => False;};
    	properties
    		Test_Props::Test_Prop => True;
    end d1.i;

	system test
		features
			output : out data port d1.i;
	end test;
	
	system implementation test.i
	end test.i;
	
end Test;
```

The instance model for `test.i` contains a single data port called `output`. This dataport has a property association for `Test_Prop`, but the data subcomponent `d2` does not appear in the instance model. Likewise we are unable to see the value of the property `Test_Prop` associated with `d2`.

**Comment by lwrage** [comment]
Duplicate, see #626
