### ISSUE TITLE
Enhancement Request:  Show Connections Between Hardware Platform and Software Components

### ISSUE THREAD

**Issue by pammathews** [osate/osate2-core#773]
I am using OSATE version 2.2.1 (osate2-2.2.1-vupdate01-win32.win32.x86_64.zip), running on Windows 7 Enterprise.  

In my OSATE project, I have a system CommonMissionProcessor that includes subcomponents:
cmpsw: process CMPThreads::CMPSoftwareProcess.impl;
sbc:  system HardwarePlatform::sbc1_mcu.dualcore;

In CommonMissionProcessor I have defined properties for binding hardware to software:
Actual_Processor_Binding => (reference(sbc.my_cpu)) applies to cmpsw.scorpion_device_manager;
Actual_Processor_Binding => (reference(sbc.my_cpu)) applies to cmpsw.track_symbology_widget;
Actual_Processor_Binding => (reference(sbc.my_cpu)) applies to cmpsw.sensor_resource_manager;	    
Actual_Processor_Binding => (reference(sbc.my_cpu)) applies to cmpsw.ccga_device_manager;	
Actual_Processor_Binding => (reference(sbc.my_cpu)) applies to cmpsw.cti_device_manager;	
Actual_Processor_Binding => (reference(sbc.my_cpu)) applies to cmpsw.advanced_display_processor;
Actual_Processor_Binding => (reference(sbc.my_cpu)) applies to cmpsw.adp_cursor_widget;

cmpsw is a process with thread subcomponents:
scorpion_device_manager:  thread ScorpionHCMSDeviceManager;
track_symbology_widget: thread HDPTrackSymbologyWidget;
sensor_resource_manager: thread SensorResourceManagementManager;
ccga_device_manager: thread CCGADeviceManager;
cti_device_manager: thread CTIDeviceManager;
advanced_display_processor: thread AdvancedDisplayProcessor;
adp_cursor_widget: thread ADPCursorWidget;

and sbc is a system [sbc1_mcu.dualcore] with processor, bus, and memory subcomponents:
my_cpu: processor HardwareParts::SingleBoardComputer1.dualcore;
my_PCI: bus HardwareParts::PCIBus;
my_EthernetBus: bus HardwareParts::EthernetBus;
my_VideoBus: bus HardwareParts::SMTPE_424_VIDEO;
my_RS422Bus: bus HardwareParts::RS_422;
my_ram: memory HardwareParts::RAM;
my_rom: memory HardwareParts::ROM;
my_PowerSupply: bus HardwareParts::PowerSupply;

The system diagram for CommonMissionProcessor does not show any graphical connection or association between the software process and the hardware platform, even though there are “processor bindings”.  

It would be descriptive/clarifying for the diagram to visibly represent the binding in the diagram (such as some type of connector line, or pop-up note or symbol when arrowing over an object to show the bound threads).

**Comment by lwrage** [comment]
@philip-alldredge Can you comment on this?

**Comment by philip-alldredge** [comment]
Bindings should appear in diagrams where a) the binding is defined in the context of the classifier being views. b) the elements involved in the binding are in the diagram. In your case, when viewing the CommonMissionProcessor  classifier, the bindings should appear as long as your have both the threads and the cpu components visible. It appears to work as expected. Have you tried increasing the nesting depth to ensure all components are visible? If it doesn't work, please provide a complete example and a description of the steps being performed to help reproduce the issue.

Additionally, there are a couple open issues to improve the properties support in the graphical editor.
osate/osate-ge#140
osate/osate-ge#146

**Comment by philip-alldredge** [comment]
After further review, I believe I better understand what the issue is. The editor currently shows bindings only if the elements involved are in the diagram. However, if I understand correctly, you would like to see an indicator that there are bindings between the contents of those model elements. In this case, include an indicator between the system and the process in question rather when the processors and threads are not included in the diagram. Is this correct?

I have opened an issue on the graphical editor issue tracker to track this issue. osate/osate-ge#197

**Comment by pammathews** [comment]
@philip-alldredge<https://github.com/philip-alldredge>
Hi Philip:  Thanks for your reply this item (#773).  Question:  Are you saying below that the editor shows bindings only if the elements involved are in the same diagram?  A hardware platform and software process may be subcomponents in a system diagram, and we would like to see an indicator that there are bindings between the hardware platform and software process.

In an example from “OSATE Class Exercise 9: Modeling Hardware Platform Components”, there is a CarSystem implementation.  The system contains a subcomponent “ecu” that represents a hardware cpu, and a subcomponent “cc” that represents a software process with software threads.  The software is “bound” to the hardware with several lines, like this generic one:
properties
Actual_Processor_Binding => (reference(ecu.cpu)) applies to cc.software_process.cc_software_thread;

The “binding” is not visible in the CarSystem diagram.  The Hardware Platform appears to be “floating” separately from the subcomponent that contains the software process.  Our desire with the feature request is to somehow show the binding with a connection between the Hardware Platform and the software process subcomponent.

Please let me know if this is enough information to clarify what we are looking for.  I can send an attachment with more information if you need it.

V/R,
Pamela Mathews
Lockheed Martin
Rotary & Mission Systems  (RMS)
2323 Eastern Boulevard
Baltimore, MD 21220
Desk:  410-682-1265
Fax:  410-682-1742
pamela.mathews@lmco.com<mailto:pamela.mathews@lmco.com>

**Comment by pammathews** [comment]
@philip-alldredge Hi Philip - Yes, we would like to see an indicator that there are bindings between the contents of model elements, such as a system and a process whose details (such as cpu's and threads) are not included in the diagram.  I agree with the wording in osate/osate-ge#197 "Improve Binding Support"
