### ISSUE TITLE
Enhancement Request:  Show Comments in OSATE Diagrams

### ISSUE THREAD

**Issue by pammathews** [osate/osate2-core#774]
I am using OSATE version 2.2.1 (osate2-2.2.1-vupdate01-win32.win32.x86_64.zip), running on Windows 7 Enterprise.  

Currently I do not know of a way to show an object property such as weight or latency in the OSATE diagrams.  Is there an AADL keyword or directive that can indicate whether to show text from the AADL source on a diagram?  Alternatively, can a note or comment box be created and placed in OSATE diagrams using the graphical editor?

The ability to add comments to diagrams could enhance their readability for reviewers.

**Comment by lwrage** [comment]
@philip-alldredge Can you comment on this?

**Comment by philip-alldredge** [comment]
Unfortunately, that is not supported at this time.

For visualizing properties such as weight and latency, there is an open issue to add that feature.
osate/osate-ge#146

I have added an additional issue to track progress on adding comments/notes to the diagram.
osate/osate-ge#187

**Comment by philip-alldredge** [comment]
Closed since this is being tracked on the osate-ge tracker.
