### ISSUE TITLE
OSATE Graphical Editor Allows Movement of Connection, Then Snaps Back

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2-core#786]
I opened a diagram view of an AADL system with several implementations connected with dashed lines. The diagram editor allows me to edit the lines (bending them, moving them) but snaps them back into place when I release the mouse. As a user, this is quite frustrating. 

I'm running   OSATE2	2.2.2.v20170216-1836

**Comment by philip-alldredge** [comment]
The graphical editor component has it's own issue tracker. Reporting issues there in the future will ensure it gets seen: https://github.com/osate/osate-ge/issues

Disabling bendpoint manipulation in this case was not intended. A fix for not being able to manipulate bendpoints for generalizations has been implemented in osate/osate-ge@ad090cb6c78039f453f261ca7accfa71c7d3130d

However, the underlying issue of the UI not reflecting what is allow is more complex than I thought. The underlying library being used, Graphiti, provides the UI for editing bendpoints. However, it does not adequately support disabling the the UI for specific instances where bendpoints are not supported. This won't be as big of an issue once editing bendpoints is more generally supported, but I agree, this is an annoying issue.

I have created an issue on the osate-ge issue tracker to track that particular issue: osate/osate-ge#191
