### ISSUE TITLE
org.osate.aadl2 depends on itself, breaks eclipse dependency tools

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2-core#797]
I was trying to figure out why the "analyze plugin dependencies" tool was breaking. Someone at Eclipse found that org.osate.aadl2 has a dependency on itself. They're fixing the Eclipse tool to gracefully handle this condition, but the dependency should still be removed. 

https://bugs.eclipse.org/bugs/show_bug.cgi?id=512464

**Comment by lwrage** [comment]
Thanks! I was running the analysis the other day and noticed that it had problems.

**Comment by stevevestal** [comment]
Was this pushed to nightly test branch last night?  I asked Eclipse to identify unused dependencies again this morning and still got an infinite loop.
