### ISSUE TITLE
Instantiation error with extended inverse feature group type

### ISSUE THREAD

**Issue by lwrage** [osate/osate2-core#818]
In the following example TestSys.fg2 is instantiated with feature in1 instead of out1. 
```
package issue
public

system TestSys
features
    fg1: feature group TestExtendedFeatureGroup;
    fg2: feature group TestInvExtendedFeatureGroup;
end TestSys;

system implementation TestSys.Impl
end TestSys.Impl;

feature group TestFeatureGroup
features
    in1: in feature;
end TestFeatureGroup;

feature group TestExtendedFeatureGroup extends TestFeatureGroup
end TestExtendedFeatureGroup;

feature group TestInvFeatureGroup
features
    out1: out feature;
inverse  of TestFeatureGroup
end TestInvFeatureGroup;

feature group TestInvExtendedFeatureGroup extends TestInvFeatureGroup
inverse of TestExtendedFeatureGroup
end TestInvExtendedFeatureGroup;

end issue;
```

**Comment by lwrage** [comment]
Used wrong issue number in commit

**Comment by AaronGreenhouse** [comment]
Problem is specifically related to inverse feature groups that DO NOT add features.  

In the extended example below, only feature `fg6`, which uses the empty inverse extended feature group is incorrect.

```
package issue
public

	system TestSys
	features
	    fg1: feature group TestFeatureGroup;
	    fg2: feature group TestInvFeatureGroup;
	    
	    fg3: feature group TestExtendedFeatureGroup;
	    fg4: feature group TestInvExtendedFeatureGroup;
	    
	    fg5: feature group TestEmptyExtendedFeatureGroup;
	    fg6: feature group TestInvEmptyExtendedFeatureGroup;
	end TestSys;

	system implementation TestSys.Impl
	end TestSys.Impl;

	feature group TestFeatureGroup
	features
    	in1: in feature;
	end TestFeatureGroup;

	feature group TestExtendedFeatureGroup extends TestFeatureGroup
	features
		in2: in feature;
	end TestExtendedFeatureGroup;

	feature group TestEmptyExtendedFeatureGroup extends TestFeatureGroup
	end TestEmptyExtendedFeatureGroup;

	feature group TestInvFeatureGroup
	features
    	out1: out feature;
	inverse  of TestFeatureGroup
	end TestInvFeatureGroup;

	feature group TestInvExtendedFeatureGroup extends TestInvFeatureGroup
	features
		out2: out feature;
	inverse of TestExtendedFeatureGroup
	end TestInvExtendedFeatureGroup;

	feature group TestInvEmptyExtendedFeatureGroup extends TestInvFeatureGroup
	inverse of TestEmptyExtendedFeatureGroup
	end TestInvEmptyExtendedFeatureGroup;

end issue;
```

**Comment by AaronGreenhouse** [comment]
Doesn't matter how many features are in the original feature group.

**Comment by AaronGreenhouse** [comment]
In the example above, the feature `in1` is in fact an `out` port.  The problem is line 1014 of `InstantiateModel.java`:

```
			if (localFeatures.isEmpty() && inverseFgt != null) {
				baseFgt = inverseFgt;
				localFeatures = inverseFgt.getOwnedFeatures();
				inverse = !inverse;
			} else {
				baseFgt = fgt;
			}
```

The feature group is in question both declares no features and declares itself to be an inverse.  So the instantiation process derives its features from the feature group named as the inverse.  In this case we don't want to do that because the feature group extends a non-empty group.  I think that is the rule that we want?

**I cannot find in the specification anything about inferring the features of "empty" inverse feature groups, but clearly this is intended from the examples in the feature group section (page 134), and I know this is how it's always been done.**

Need some more opinions here.

**Comment by lwrage** [comment]
If the "empty" inverse feature group E extends another feature group F then it should inherit F's features, so it's not really empty, and we don't infer its features from the inverse. I can't think of another rule that would make sense.

**Comment by AaronGreenhouse** [comment]
Okay, this was easy to fix, I think.  

Just changed

```
			if (localFeatures.isEmpty() && inverseFgt != null) {
```

to

```
			if (localFeatures.isEmpty() && inverseFgt != null && fgt.getExtended() == null) {
```

**Comment by AaronGreenhouse** [comment]
Need to make unit test if I can stpo getting confused every time I look at the feature groups/inverse feature groups.
:-)

**Comment by AaronGreenhouse** [comment]
Added JUnit test
