### ISSUE TITLE
FHA: MIL-STD-882 missing fields

### ISSUE THREAD

**Issue by lwrage** [osate/osate2-core#825]
FHA report does not contain the following MIL-STD-882 defined fields: FailureEffect, Mishap, Risk, SeverityCategory, ProbabilityLevel, QuantitativeProbability, TargetSeverityLevel, TargetProbabilityLevel, SafetyReport. It would be beneficial to allow selection of elements used in the report, including the elements currently contained in an FHA report, i.e., Error,  Hazard Description, Crossreference,  Functional Failure,  Operational Phases,  Environment,  Severity,  Likelihood, Verification, and  Comment.

**Comment by reteprelief** [comment]
Fixed by osate/osate2-core@226ef4d8d2f4bdf8da5385f8dc6bd33ae88e2d87
