### ISSUE TITLE
FHA: ARP4761 takes priority over MIL-STD-882

### ISSUE THREAD

**Issue by lwrage** [osate/osate2-core#827]
When defining both ARP4761 and MIL-STD-882 hazards in the model, the ARP4761 FHA takes priority over MIL-STD-882 FHA. It would be beneficial to allow populating both types of hazards and then allow selection of which type of hazard to include in the FHA report.

**Comment by sprocter** [comment]
As we support additional analysis techniques (ie, STPA / SAFE, some potential security-integrated analysis, etc.) the "Hazards" property may become increasingly overloaded. Would it be worth looking at more sophisticated ways of running multiple techniques off a shared, base "Hazards" property with technique-specific extensions? This may not even require a technical solution, but rather just a way we organize / define the property sets that support each analysis technique.
