### ISSUE TITLE
Lost reference to renamed project

### ISSUE THREAD

**Issue by lwrage** [osate/osate2-core#831]
If one project is dependent on another.  If the project that is being dependent upon is renamed, the reference is lost.

**Comment by lwrage** [comment]
To make this clearer: A depends on B, B is renamed to C. A still depends on B, which doesn't exist any longer. Renaming B to C should update the project reference in A to C. 
Maybe: Add resource listener in org.osate.workspace to react to project renames.

**Comment by AaronGreenhouse** [comment]
Wow amazing that Eclipse doesn't do this automatically considering that the project references is a core Eclipse functionality.

**Comment by AaronGreenhouse** [comment]
Need to
1. Figure out how to access project references
2. Use a ResourceListener to detect project renames
3. Update the references

**Comment by AaronGreenhouse** [comment]
`IProject.getReferencingProjects()` tells which projects depend on the receiver

**Comment by AaronGreenhouse** [comment]
To reset the dependencies you have to use  `IProject.getDescription()` and then `IProjectDescription.getReferencedProjects()`, `IProjectDescription.setReferencedProjects()`, and finally `IProject.setDescription()`.

**Comment by lwrage** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=2855

**Comment by AaronGreenhouse** [comment]
The `ResourceChangeListener` should be managed `OcateCorePlugin`

**Comment by AaronGreenhouse** [comment]
Doesn't seem like Eclipse is going to fix this, but I cannot really see why not.

**Comment by AaronGreenhouse** [comment]
Fixed this.  The IResourceChangeListener is managed by OsateCorePlugin.  Makes sure that any 2 projects that have an AADLNature have the reference between them kept in sync.  Open works for projects that are open in the workspace.

Tested this by putting `package1` in project `p1`:
```
package package1
public
	system T
		
	end T;
end package1;
```

and package `package2` in project `p2`:
```
package package2
public
	with package1;
	
	system s
		
	end s;
	
	system implementation s.i
		subcomponents
			q: system package1::T;
	end s.i;
end package2;
```

and making project `p2` have a reference to `p1`.

Renamed project `p1`, and checked that `p2` was updated in the properties view.  (It was.)  

Tried this with several projects depending on `p1` as well, and everything worked.
