### ISSUE TITLE
AADL Property Values option usage

### ISSUE THREAD

**Issue by pioneerxian** [osate/osate2-core#856]
when using ocarina plug-in generated code, the Console tab of OSATE2 showed information:"Backends: 
fatal error : This process has to be bound to a processor".I try to select the corresponding element to make the set properties.However, right-click menu of AADL Property Values option is grey and disabled.
  Please comment, how to set the properties of the corresponding element, or OSATE2 has cancelled this functionality.

**Comment by lwrage** [comment]
From your description I'm not sure how to reproduce the issue. Could you please provide an example model and describe the steps to reproduce the issue in more detail?

**Comment by pioneerxian** [comment]
Dear lwrage, Thank you very much for your answer to my request.Would you be so kind as to provide an E-mail address? I could send my examples and detailed description of operation to you.Thanks in advance.

**Comment by pioneerxian** [comment]
[question_to_ask.docx](https://github.com/osate/osate2-core/files/1172344/question_to_ask.docx)

**Comment by lwrage** [comment]
I'd prefer if you created a small example model and add it as a comment here. Also, i cannot access your Word document. Please copy the text into a comment.

**Comment by pioneerxian** [comment]
Dear lwrage,Thank you very much for your answer to my request.
    The example in the package derived from GitHub, which is used to demonstrate the code generation for DeOS, VxWorks and POK. 
    The system of the example includes three functions:
    sensor : that send an altitude data to the filters. There are two sensors.
    filtering : that filters data from the sensors and remove inconsistent data.
    actuator: receives data from the filter and take action.
    The example shows how to deploy the same system on the following targets: DeOS and VxWorks653.
    Recently I make a study on automatic code generation through OSATE based on AADL. By imitating this example and the understanding of the example, I set an example,test_demo.
To generate the code by following these steps:
    step1：
    open test_codegen.aadl file in the test_demo project
    step2：
    choose “System Impl integration.single_partition_VxWorks” in Outline tab.
    step3:
    choose “Ocarina Bridge” in “OSATE” tab,then choose “Generate POK/VxWorks Code”
    It is a pity that my example of modeled generated compile error in the Console tab. the following picture shows the error. "fatal error : This process has to be bound to a processor".
    So that's my problem in detail.

**Comment by pioneerxian** [comment]
![examples_from_github](https://user-images.githubusercontent.com/30172911/28600510-08ebea4a-71e5-11e7-8496-82c4a5930f4c.png)
![mistake_information](https://user-images.githubusercontent.com/30172911/28600511-08ec4238-71e5-11e7-8307-adbf8c4cc342.png)
![step1](https://user-images.githubusercontent.com/30172911/28600512-08eddf62-71e5-11e7-898a-f1129dabb860.png)
![step2](https://user-images.githubusercontent.com/30172911/28600513-08f36482-71e5-11e7-84c6-20eadbcf4d41.png)

**Comment by pioneerxian** [comment]
first picture: original example
second picture: mistake information
third picture: my test example(step1)
fourth picture: step2

**Comment by joeseibel** [comment]
The *AADL Property Values* view allows simple editing of properties, but not all editing.  `Actual_Processor_Binding` needs to be specified as a contained property association, which cannot be done with the *AADL Property Values* view, but must be done by using the text editor.  If you look at the example file *integration.aadl*, you will notice on line 69 an example of this property being set:
`actual_processor_binding => (reference (module.partition1)) applies to pr;`
