### ISSUE TITLE
IMV-Flow Highlighting

### ISSUE THREAD

**Issue by lomoo15** [osate/osate2-core#857]
some flows cannot be shown in IMV . Why?

	--MMM START
	process AC_GSM
		features
			init_gfm : out event port;
		instruction_pcm : out event data port;
			instruction_app : out event data port;
			instruction_gfm : out event data port;
		flows
			fs1 : flow source instruction_pcm;
			fs2 : flow source instruction_app;
			fs3 : flow source init_gfm;
			fs4 : flow source instruction_gfm;
	end AC_GSM;
	
	process implementation AC_GSM.i
	end AC_GSM.i;
	
	process MMM_GSM
		features
			instruction_in : in event data port;
		flows
			fs1 : flow sink instruction_in;
	end MMM_GSM;
	
	process implementation MMM_GSM.i
	end MMM_GSM.i;
		
	system MMM
		features
			init_gfm : out event port;
		port_mmm : in out event data port;
		flows
			fs1 : flow source init_gfm;
			fs2 : flow source port_mmm;
			fs3 : flow source port_mmm;
	end MMM;
	
	system implementation MMM.i
		subcomponents
			processor_AC : processor CPU;
			processor_MMM : processor CPU;
			memory_MMM : memory RAM;
			AC_GSM : process AC_GSM.i;
			MMM_GSM : process MMM_GSM.i;	
		connections
			conn1 : port AC_GSM.init_gfm -> init_gfm;
			conn2 : port AC_GSM.instruction_app -> MMM_GSM.instruction_in;
			conn3 : port AC_GSM.instruction_pcm -> port_mmm;
			conn4 : port AC_GSM.instruction_gfm -> port_mmm;
		flows
			ETE1 : end to end flow AC_GSM.fs2 -> conn2 -> MMM_GSM.fs1;
			fs1 : flow source AC_GSM.fs3 -> conn1 -> init_gfm;
			fs2 : flow source AC_GSM.fs1 -> conn3 -> port_mmm; 
			fs3 : flow source AC_GSM.fs4 -> conn4 -> port_mmm;
		properties
			actual_processor_binding => (reference(processor_AC)) applies to AC_GSM;
			actual_processor_binding => (reference(processor_MMM)) applies to MMM_GSM;
			actual_memory_binding => (reference(memory_MMM)) applies to MMM_GSM;
	end MMM.i;
	--MMM END

![default](https://user-images.githubusercontent.com/30229996/28261691-dc36a464-6b12-11e7-83dc-e270962647e8.JPG)

**Comment by lwrage** [comment]
The IMV plugin is currently unmaintained. Work has been started to integrate its functionality into the main graphical editor.
