### ISSUE TITLE
about the mechanism of Ocarina plugin

### ISSUE THREAD

**Issue by pioneerxian** [osate/osate2-core#878]
Now I can use OSATE tools to generate C code based on the VxWorks653 System through adding the plugin Ocarina,But I don't understand the mechanism of Ocarina plugin. In simple terms, I don't know the code project in which each C file is on behalf of the meaning and the file name is how to produce.Here is for C code in the following comment .Please people who understand the knowledge of this to help solve the problem or provide some information about the Ocarina on code genearation, thank you very much.

**Comment by pioneerxian** [comment]
The framework of generated code:
activity.h
activity.c
deployment.h
deployment.c
gtypes.h
gtypes.c
marshallers.h
marshallers.c
naming.h
naming.c
request.h
request.c
subprograms.h
subprograms.c
main.c

**Comment by joeseibel** [comment]
This is more of a question for Ocarina instead of OSATE. Please refer to [Open AADL](http://www.openaadl.org/).  You can also post issues on [Ocarina's GitHub repository](https://github.com/OpenAADL/ocarina).
