### ISSUE TITLE
Set Classifier for a Virtual Processor Subcomponet

### ISSUE THREAD

**Issue by pioneerxian** [osate/osate2-core#880]
Dear Joe,there is a problem again,I want to ask for consult.The example "codegen-demo" derived from GitHub, which is used to demonstrate the code generation for DeOS, VxWorks and POK.
    Recently I make a study on automatic code generation through OSATE based on AADL. By imitating this example and the understanding of the example, I set an example, "test_demo". In the process of imitation learning,I have an operation problem to consult. In the "codegen-demo" example ,the program of "integration.aadl" has a system type "integration.single_partition_vxworks". One part of "integration.single_partition_vxworks" named as "module" has a virtual processor subcomponent "partition1". To analyze from "partition1"，the type of which is set to "codegen_demo::platform::partition.vxworks" . But in my example "test_demo",I want to set type for it 
through right-clicking on it and select "Set Classifier" command.To my disappointed,problem occurred,"An error occured modifying the AADL model.Unexpected type:org.osate.aadl2.iml.VirtualProcessorSubcomponetImpl".
    Please comment, how to operate to set type for the virtual processor subcomponent "partition1".The problem which  I consult you last time may be associated with AADL program statement"actual_processor_binding => (reference (module.partition1)) applies to pr;"

**Comment by pioneerxian** [comment]
![1](https://user-images.githubusercontent.com/30172911/29103824-80691f24-7cf4-11e7-930c-0a5983f80d28.png)
![2](https://user-images.githubusercontent.com/30172911/29103825-807cddf2-7cf4-11e7-98d9-c17d5d3e0db8.png)
![3](https://user-images.githubusercontent.com/30172911/29103826-809091ee-7cf4-11e7-88f4-94490875baad.png)
![4](https://user-images.githubusercontent.com/30172911/29103827-809100de-7cf4-11e7-9f17-b40b09be74e6.png)
![5](https://user-images.githubusercontent.com/30172911/29103828-80911786-7cf4-11e7-9311-ebc82f26abb4.png)

**Comment by pioneerxian** [comment]
the first,second ,third picture are all from model example "codegen-demo".
the fourth,fifth picture are from my example "test_demo".

**Comment by philip-alldredge** [comment]
You have come across a bug in the graphical editor portion. I'll look into and fix it. As a workaround, you can go into the textual AADL and modify the subcomponent:

```
partition1: virtual processor partition.vxworks;
```

**Comment by philip-alldredge** [comment]
The issue has been fixed and will be available in the next release.
