### ISSUE TITLE
OSATE allows subprograms to have in event ports

### ISSUE THREAD

**Issue by rinsley** [osate/osate2-core#910]
In the AS5506C standard, page 71, it lists the types of port features allowed on subprograms, which are limited to out event port and out event data port.

However, the AADL text editor does not give an error if you add an in event port to a subprogram. Example (does not cause errors in the editor):

	subprogram sp
		features
			e1: in event port;
			e2: in out event port;
			e3: in event data port;
			e4: in out event data port;
	end sp;

**Comment by lwrage** [comment]
Need to add a validation.
