### ISSUE TITLE
Cannot connect to feature in nested feature group

### ISSUE THREAD

**Issue by rinsley** [osate/osate2-core#922]
I'm getting this error from the AADL text editor: "Nested Feature Groups are only allowed for connections going across from Subcomponent to Subcomponent".

Here is a snippet that causes the error:

	system Parent
		features
			FG1: feature group FG1;
	end Parent;

	system implementation Parent.impl
		subcomponents
			Child: system Child.impl;
		connections
			Connection1: feature Child.F1 -> FG1.FG2;
			Connection2: feature Child.F1 -> FG1.FG2.F3;
	end Parent.impl;

	system Child
		features
			F1: out feature;
	end Child;

	system implementation Child.impl
	end Child.impl;

	feature group FG1
		features
			F2: out feature;
			FG2: feature group FG2;
	end FG1;

	feature group FG2
		features
			F3: out feature;
	end FG2;

In this example, Connection1, which goes to a feature in a feature group is fine, but Connection2, which goes to a feature in a nested feature group is not fine.

It looks like perhaps this is related to Section 9.1(L7) of the AADL specification, which says "If the feature connection is between two subcomponents, then nested features can be referenced arbitrarily deep. For connections up and down the hierarchy, the reference to a subcomponent feature is limited to a single feature identifier."

However, strictly speaking, the situation here isn't what's covered by the standard. The standard says "the reference to a _subcomponent_ feature" is what's limited a single identifier. In the example above, it's not a reference to a _subcomponent_ feature that's causing an error, it's a reference to a nested feature on the component itself. If the limitation is meant to cover both ends of the connection, the wording in the standard should probably omit subcomponent and say "the reference to a feature is limited to a single feature identifier." Then again, if that was the meaning, I would expect Connection1 to also cause an error because it uses more than one feature identifier. So, perhaps both OSATE's behavior and the standard need to be revised here.

Also, on the whole, this limitation is inconsistent and unexpected... Feature connections to nested features are okay if they are going across the hierarchy, but some or all of the time they are not okay if they are going up and down the hierarchy... it seems like they should always be allowed to any nested feature.

**Comment by lwrage** [comment]
Reaching down arbitrarily deep into feature groups is allowed only for connections between subcomponents, but not for connections that go up or down the hierarchy. This is as intended. If the wording in the standard is unclear, please file an issue at https://github.com/saeaadl/aadlv2.2/issues

**Comment by rinsley** [comment]
Okay, I filed an issue against the standard. But if you saying the interpretation of the standard is that reaching down into feature groups is prohibited for connections up and down the hierarchy, then I still don't think OSATE's behavior here is correct because it seems like that would mean Connection1 should cause an error as well.
