### ISSUE TITLE
Instantiated Feature Group Connection Reference pointing to wrong Feature Instance

### ISSUE THREAD

**Issue by rinsley** [osate/osate2-core#923]
I've encountered a situation where feature group connection references don't seem to be instantiating correctly. See this example:

	package FeatureGroupTest
	public
	
		feature group ParentGroup
		features
			NestedOutputGroup: feature group OutputGroup;
		end ParentGroup;
	
		feature group OutputGroup
		features
			Out1: out data port;
		end OutputGroup;
	
		system Sys1
		features
			PG: feature group ParentGroup;
		end Sys1;
	
		system Sys2
		features
			PG: feature group inverse of ParentGroup;
			OutputGroup: in feature group inverse of OutputGroup;
		end Sys2;
	
		system Main
		end Main;
	
		system implementation Main.impl
		subcomponents
			Sys1: system Sys1;
			Sys2: system Sys2;
		connections
			C1: feature group Sys1.PG.NestedOutputGroup -> Sys2.PG.NestedOutputGroup;
			C2: feature group Sys1.PG.NestedOutputGroup -> Sys2.OutputGroup;
		end Main.impl;
	
	end FeatureGroupTest;

The first connection instantiates as expected. The second does not.

In the instance model XML, this is what the connection reference looks like for the first connection . It goes from a feature on the first component, @componentInstance.0, to a feature on the second component, @componentInstance.1, as expected.

    <connectionReference context="/" source="//@componentInstance.0/@featureInstance.0/@featureInstance.0/@featureInstance.0" destination="//@componentInstance.1/@featureInstance.0/@featureInstance.0/@featureInstance.0">

However, this is what the connection reference looks like for the second connection. The source and destination are both referencing features on @componentInstance.0:

    <connectionReference context="/" source="//@componentInstance.0/@featureInstance.0/@featureInstance.0/@featureInstance.0" destination="//@componentInstance.0/@featureInstance.0/@featureInstance.0/@featureInstance.0">

The issue is also visible in a textual instance for the second connection (the connection goes from Sys1 to Sys2, but it says both of the features are on Sys1):

	complete portConnection "Sys1.PG.NestedOutputGroup.Out1 -> Sys2.OutputGroup.Out1" : Sys1.PG.NestedOutputGroup.Out1 -> Sys2.OutputGroup.Out1 {
		Sys1.PG.NestedOutputGroup.Out1 -> Sys1.PG.NestedOutputGroup.Out1 : FeatureGroupTest::Main.impl:C2 in parent
	}

**Comment by philip-alldredge** [comment]
Since the graphical editor uses connection references when visualizing connections, this has an impact on it as well.

**Comment by AaronGreenhouse** [comment]
I see this too

**Comment by AaronGreenhouse** [comment]
Soemthing is probably wrong with ConnectionInfo.createConnectionInstance() lines 214 to 222.  This is the only place ConnectionReferences are created.

**Comment by AaronGreenhouse** [comment]
Problem is most likely in ConnectionInfo.resolveFeatureInstance()

**Comment by AaronGreenhouse** [comment]
Okay.  So lines 252 to 259 of ConnectionInfo.java in the method resolveFeatureInstance() return 

So the process that creates the ConnectionReference object uses the method resolveFeatureInstance() to get the destination of the connection reference.  But, lines  lines 252 to 259 of ConnectionInfo.java in the method resolveFeatureInstance() return based on the SOURCE of the connection reference.  So in this case, the destination of the connection reference is going to be a feature of the source component.  

I don't understand enough of what is really going on to know why the code was written this way or what the intent is.  But this is definitely fishy.

**Comment by AaronGreenhouse** [comment]
Lutz told me Peter wrote this so I e-mailed him, but he says that Lutz wrote it originally.

**Comment by reteprelief** [comment]
Just check the Git history on the file ☺

**Comment by AaronGreenhouse** [comment]
I think I fixed this, not sure if it messes up other things or not.  There was basically one spot (line 259) where a feature from the SOURCE of the connection is returned.  Everyone where else a feature from the DESTINATION is returned.  I changed this line to return the corresponding destination feature.  Now the above example works correctly.

**Comment by AaronGreenhouse** [comment]
Added JUnit tests
