### ISSUE TITLE
Resolute Standard Library Errors

### ISSUE THREAD

**Issue by dpgluch** [osate/osate2-core#940]
See the attached graphic. These are errors that do not show up in the navigator.
![capture](https://user-images.githubusercontent.com/24554086/32853682-0e70457e-ca0a-11e7-9408-74c7e8908c97.JPG)

Also, this may be related, even though the StdLib computational function 'connected' 

connected(a : component, conn : connection, b : component) : bool =
  parent(source(conn)) = a and parent(destination(conn)) = b

shows no errors, there is a reference error in the claim function 'is_connected' shown in the graphic below. 

![capture2](https://user-images.githubusercontent.com/24554086/32853916-ddded91a-ca0a-11e7-9270-96be31451809.JPG)

If I define 'connected' locally the claim function 'is_connected' is fine.

**Comment by backesj** [comment]
Do the errors go away if you clean your workspace?

What version of OSATE are you using? Everything seems to work fine in a
fresh copy of 2.2.3. I'll download 2.3.0 and confirm if I see the same
behavior.

- John

**Comment by backesj** [comment]
It seems to be broken in 2.3.0. I think I know what is going on. I'll
submit a fix for this soon.

**Comment by lwrage** [comment]
Fixed in smaccm/smaccm@8f2fa6c659d44a45de9df3873b98add14d7d34b8
