### ISSUE TITLE
Weight Workflow should attach weight property to classifier declarations

### ISSUE THREAD

**Issue by AaronGreenhouse** [osate/osate2-core#941]
The property editor dialog should show the classifier for each component.  If there is no classifier declared, the property should not be editable for the component, but the dialog should allow the classifier to be declared.  Furthermore the dialog should track which components have the same classifier, so that if the property is modified for one component, it is updated (in the dialog only) for the other components that have the same classifier.  When the dialog actually sets the property value, it should update the declarative model for the classifier and the instance model for the affects components.

**Comment by AaronGreenhouse** [comment]
We discussed complications that arise when there are subtypes of the classifiers, and components that are of different types along the hierarchy, but then decided to ignore that case because it's probably not going to arise.  It doesn't make sense really to change the weight property along the classifier hierarchy because it would need to be kept consistent (i.e., a subtype shouldn't weigh less).

So just a note to say we thought of this already and have decided to ignore it.

**Comment by AaronGreenhouse** [comment]
The Weight Limit and Weight Contribution editor boxes have been updated to have a column to show the classifier of the component.  This is actually handled by the super class SingleTreeDialog: I added a flag to the constructor about whether it should show this column or not.

**Comment by AaronGreenhouse** [comment]
Lutz now says that the dialog should not be used to edit the classifier.

**Comment by AaronGreenhouse** [comment]
SingleTreeDialog has been modified as follows (this summarizes things I may have said above):

- The constructor takes a flag indicating if a column should be shown that displays the classifier of the component.  If no classifier is specified, the columns shows "No Classifier Specified" in red.
- If the classifier column is showing, then the property values for the component are only editable if the classifier is actually specified.

**Comment by AaronGreenhouse** [comment]
Updated SingleTreeDialog so that if the classifier column is being used, then editing the value of a property will change the value of the proeprty for all component instances with the same classifier.

TODO: change how the properties are added to the models:

- The classifier in the declarative model is updated
- The component instance in the instance model is updated (this is being done already actually)
- The property is NOT set as an applies to property association in the declarative model (as is being done now).

**Comment by AaronGreenhouse** [comment]
Updated WeightWorkflow so that the properties are written to the component classifier of the components, not written as "applies to" properties on the root of the system.  Modified/added methods to the AbstractPropertyDialog and SingleTreeDialog to support this.

I believe this is complete now.

**Comment by joeseibel** [comment]
Branch **941_Weight_Workflow** has been merged into **master** and deleted.
