### ISSUE TITLE
How i deal with @// when using Java operate aaxl file in the way of DOM?

### ISSUE THREAD

**Issue by magichan** [osate/osate2-core#947]
Hi, Every one. 
For some reason,  I only can use java to operate `aaxl` file in the way of DOM. I know the `aaxl`  file  follow the `XML Schema` specification. 
But i have some problem in `inMode="#//@ownedPublicSection/@ownedClassifier.41/@ownedMode.0"`, like following example:
```
<ownedThreadSubcomponent name="fg1" inMode="#//@ownedPublicSection/@ownedClassifier.41/@ownedMode.0" threadSubcomponentType="#//@ownedPublicSection/@ownedClassifier.27">
        <ownedModeBinding parentMode="#//@ownedPublicSection/@ownedClassifier.41/@ownedMode.0"/>
</ownedThreadSubcomponent>
```
I want to get the value of `inMode`, But i don't find java function/java object  to parse  `"#//@ownedPublicSection/@ownedClassifier.41/@ownedMode.0"`

Is this format of xml private specification used in aaxl, or public specification? and How I parse it to get the value of `InMode` in java?

**Comment by lwrage** [comment]
Please ask questions on the OSATE Google group.
