### ISSUE TITLE
Contributed models do not show up in AADL navigator

### ISSUE THREAD

**Issue by Etienne13** [osate/osate2-core#948]
We use the aadlcontribution extension point of osate to contribute AADL models of our plugins. The models are loaded, and we can reference them but the do not appear in the AADL navigator.

They are contained in a directory "aadl_resources/package/" aadl_resources appears in the Navigator but it looks empty.

An example of contributed file in our plugin.xml file is:

      <aadlcontribution
            file="aadl_resources/package/POSIX_runtime.aadl"
            id="fr.tpt.aadl.packages.posix_runtime.aadlcontribution"
            name="POSIX-Runtime">
      </aadlcontribution>

It seems to be a bug in the display of the AADL Navigator.

Best regards,
Etienne.

**Comment by lwrage** [comment]
We cannot reproduce this. Do you have a *.genmodel in your plugin? Contributed models don't work in plugins that also contain a genmodel file. See #527 for details.

**Comment by Etienne13** [comment]
Hello,

I don’t think my issue is related to the one you referenced.

To reproduce the issue, here is a simple procedure:

1) create a new plugin project in the Eclipse you use for development.
2) add a folder f1
3) add a folder f2 inside f1
4) add an AADL model m1.aadl in f1
5) add an AADL model m2.aadl in f2
6) add a plugin.xml file
7) add plugin.xml and f1 in the binary build of the project
8) launch osate with this new plugin

Here is a project with artefacts created in steps 1 to 7 above: 
[test-issue.zip](https://github.com/osate/osate2-core/files/1513118/test-issue.zip)

In my current configuration, f1/m1.aadl does appears but not f1/f2/m2.aadl

Best regards,
Etienne.

**Comment by lwrage** [comment]
It's a bug in the logic that processes contributed directories. Currently it does not work for more than one level.

**Comment by AaronGreenhouse** [comment]
I see this.  Working on it now.

**Comment by AaronGreenhouse** [comment]
Problem is in AadlNavigatorContentProvider.getChildren() in the lines where it tries to filter the complete list of contributed files into the ones that are children of the given element:

```
			Stream<URI> inDirectory = PluginSupportUtil.getContributedAadl().stream().filter(uri -> {
				OptionalInt firstSignificantIndex = PluginSupportUtil.getFirstSignificantIndex(uri);
				if (firstSignificantIndex.isPresent() && firstSignificantIndex.getAsInt() < uri.segmentCount() - 1) {
					List<String> uriDirectory = uri.segmentsList().subList(firstSignificantIndex.getAsInt(), uri.segmentCount() - 1);
					System.out.println(uri + " :: " + uriDirectory + " :: " + directoryPath.equals(uriDirectory));
					return directoryPath.equals(uriDirectory);
				} else {
					return false;
				}
			});
```

**Comment by AaronGreenhouse** [comment]
The filter fails if the current `directoryPath` is a prefix of the elements uriDirectory.

**Comment by AaronGreenhouse** [comment]
The right thing to have done here would be to build a tree of the contributed items during startup instead of trying to recreate the tree on the fly based on the paths through the tree.  But that's not going to change now.  The trick here is going to be to avoid creating multiple copies of the  same child directory, such as when we are opening the folder `f1`, and we have contributed files `f1\f2\x.aadl` and `f1\f2\y.aadl`.

**Comment by AaronGreenhouse** [comment]
Fixed this.   Replaced the equality test with a prefix test.

The Java streams and aggregators are taking care of the duplicate problem.
