### ISSUE TITLE
null pointer exception when typing model

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2-core#959]
in end ID validation:
```
package issue14
public
	device battery
		features
			socket: requires bus access mybus;
	end battery;
	bus mybus
	
	end mybus;
	system power
		features
			line1: requires bus access mybus;
			line2: requires bus access mybus;
	end power;
	system implementation 
end issue14;
```
In connection declaration in validation method checkReferencesToInternalFeatures

**Comment by reteprelief** [comment]
Actually there are lots of null pointer exceptions being thrown in validation methods. They just don't show as the validation method just exits. You can see them when you monitor for null pointer exceptions in debug mode.

**Comment by lwrage** [comment]
Does this lead to incorrect behavior or is this just a cleanup activity?
