### ISSUE TITLE
Instance model with abstract instance instead of process

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2-core#961]
The instance model contains an abstract component instance pointing to the process subcomponent, whose classifier is abstract. Should be process.

package abstractprocess
public
	system s
	end s;
	system implementation s.i
		subcomponents
			p: process a;
	end s.i;
	abstract a
		end a;
end abstractprocess;

**Comment by AaronGreenhouse** [comment]
This is caused by the instantiation process getting the component category from the classifier of the component.  This in turn, seems to be done to deal with prototypes.

**Comment by lwrage** [comment]
I think the category can be determined as follows:

If the classifier is not abstract then use its category (and maybe check that the subcomponent either has the same category or is abstract). 
If the classifier is abstract then use the category from the subcomponent.

Only if both are abstract the component instance should be abstract.
If both are not abstract then they must have the same category. If the categories are different, validation should already have reported an error, and we don't instantiate models with errors. It can't hurt if the instantiator checks again, though.

**Comment by AaronGreenhouse** [comment]
I'm confused why we shouldn't just use the component category as stated in the Subcomponent declaration:

- If it's abstract, then the given classifier (if any), must be abstract, so we must generate an abstract subcomponent.
- If it's not abstract, then the given classifier (if any), must have the same category (so we use he declared one), or it must be abstract, in which case we want to use the category from the subcomponent declaration. 

What case am I missing that looking at the classifier is even necessary?

**Comment by lwrage** [comment]
If abstract subcomponent refers to an abstract prototype, the prototype actual can be of any category.
With refinement, the new category is listed with the refined subcomponent. When using prototypes it is only in the classifier.

**Comment by AaronGreenhouse** [comment]
So here's a case that current throws an exception.  I realize this is model that in a strict sense is incomplete nad probably should't be allowed to be instantiated.

	package Package
		public
			system s
			end s;
	
			system implementation s.i
				prototypes
					X: bus;
				subcomponents
					b: bus X;
			end s.i;
	end Package;

Instantiating s.i causes an exception because the subcompenent 'b' doesn't have a classifier at all.

**Comment by AaronGreenhouse** [comment]
> If abstract subcomponent refers to an abstract prototype, the prototype actual can be of any category.
With refinement, the new category is listed with the refined subcomponent. When using prototypes it is only in the classifier.

Got it, that would be this situation here:

	package package2
	public
		system SS
		prototypes
			X: abstract;
		end SS;

		system implementation SS.i
		subcomponents
			s1: abstract X;
		end SS.i;
	
		bus B1
		end B1;
	
		bus implementation B1.i
		end B1.i;

		system SSS
		end SSS;
	
		system implementation SSS.i
		subcomponents
			sub2: system SS.i (X => bus B1.i);
		end SSS.i;
	end package2;

**Comment by AaronGreenhouse** [comment]
Fixed this.

But there are still exceptions that show up when a prototype is unbound, but that should probably have a new issue opened for it.

**Comment by AaronGreenhouse** [comment]
Need to create testing class

**Comment by AaronGreenhouse** [comment]
Added JUnit test class
