### ISSUE TITLE
Possible to have multiple packages in the same .aadl file?

### ISSUE THREAD

**Issue by paolo-crisafulli** [osate/osate2-core#979]
Hi all,
I'm trying to reuse AADL packages from Ocarina in a project that I'm editing with Osate.
Ocarina provides a huge .aadl file, ocarina_components.aadl, containing several useful packages definition (sample attached, as .txt file because Github rejects .aadl).

[ocarina_components.txt](https://github.com/osate/osate2-core/files/1572400/ocarina_components.txt)

Osate considers this file as invalid, mainly because it contains more than one package object.

I have checked this fact with a much simpler example:

    package test
    public
    end test;

    package test2
    public
    end test2;

This won't be parsed by Osate which reports "Incomplete package or property set declaration", referring to the 'package test2' line.

Is this a desirable behavior? 
In the AADL specification, I can't find a mention of the fact that .aadl files should contain only one package object.
Thank you in advance for your help.

**Environment:**
Ubuntu LTS 16.04
Osate 2.3.0 (product version, stable)
Ocarina v2017.1

**Comment by lwrage** [comment]
OSATE doesn't support multiple packages per file. The AADL specification neither requires nor forbids it. We are not planning on changing this in OSATE 2.

**Comment by lwrage** [comment]
BTW, the OSATE Google group would be a better place to discuss items like this.

**Comment by paolo-crisafulli** [comment]
Thank you for your answers (cf. #981), I'll post my next questions to the Google group as suggested.
