### ISSUE TITLE
Cannot customize AADL_Project

### ISSUE THREAD

**Issue by paolo-crisafulli** [osate/osate2-core#981]
Hi all,

I need to customize my `AADL_Project` property set, so I have followed the instructions given in SEI's wiki (https://wiki.sei.cmu.edu/aadl/index.php/Customizing_AADL_Project).

You can find the complete sample project [in gist](https://gist.github.com/paolo-crisafulli/1d2bac2bea11a78a5c64cc5cfd6bdd6b), to reproduce the issue: I'm adding an `Ada` enumeration value to the `Supported_Source_Languages`, that I'm using in file components.aadl. The Osate parser reports "Couldn't resolve reference to Property Constant, Property Definition, Enumeration or Unit literal 'Ada'. For classifier references use classifier( <ref> )."
So the default `AADL_project` is not shadowed as expected and I can't customize AADL_Project, as allowed by the standard.

Thank you in advance for your help.

Paolo

**Comment by lwrage** [comment]
The description on the Wiki is outdated, and I've deleted it. 
In OSATE 2, create AADL_Project.aadl in some project in the workspace, copy the existing content and modify. Then use the command 'Set as AADL Project property set' to switch to the modified version.
If you get name resolution errors restart OSATE. It may also be necessary to clean all projects in the workspace. 
If you have questions, please ask on the OSATE Google group.
