### ISSUE TITLE
Add property to control max number of enumerated SOMs

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2-core#987]
There is currently a hard-coded limit on the number of SOMs that will be enumerated into the instance file.  Add a property that allows users to change this upper bound if desired.  A property is suggested rather than an Eclpse/OSATE preference because this limit will be model-dependent, larger for some models and smaller for others.

**Comment by lwrage** [comment]
I don't really like the idea of a tool specific property. Would it be sufficient to have a preference setting per project? 
@reteprelief  Any thoughts?

**Comment by stevevestal** [comment]
My $0.02: A preference setting would address the need to have this user-adjustable.  Putting this on a project mostly addresses the fact this is model-dependent.  Some projects declare multiple root system implementations for alternative configurations of a system, but it seems likely they would be similar enough to use a common upper bound, and there's an obvious work-around should the need arise.

I would ask, if you are adding a preference for this somewhere, to add a check-box that allows a users to turn off OSATE SOM enumeration or allow 0 with a special interpretation.  The reason is that third-party developers might create their own mode-handling frameworks that offer different mechanisms to manage state space explosion (such as ourselves).  It's an R&D area with lots of snakes in the grass, and perhaps domain-specific where there is no one single way to do this best for all models.  As you note, it is tool-dependent.  (A trivial way to do this would be to allow a limit of 0 and either suppress the error message or turn it into a warning.  It's not a big deal, it would just avoid possibly confusing users with a false positive.)

**Comment by AaronGreenhouse** [comment]
1. Figure out how to add project-specific properties to a project and control them via the preferences panel.
2. Create property for setting the SOM enumeration limit.
3. See what are the consequences of turning off SOM enumeration.

**Comment by lwrage** [comment]
I think we should focus on getting the preference done for 2.3.2. Completely turning off SOM generation is less important and could be added later.

**Comment by AaronGreenhouse** [comment]
Need to use ProjectScope properties: https://stackoverflow.com/questions/21269281/eclipse-nature-specific-project-properties

We actually use these already in the workflow stuff.

Need to use a `org.eclipse.ui.propertyPages` extension point set the editor page for it.


Going to add a property `org.osate.aadl2.instantiation.som_limit` with the scope qualifier `org.osate.aadl2.instantiation`.

**Comment by AaronGreenhouse** [comment]
Done

**Comment by AaronGreenhouse** [comment]
Closed by accident.  Reopened.
